const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),puppeteer=require('puppeteer');
const {createService}=require('../scripts/offline-http.cjs'),{load}=require('../scripts/load-institutional-source.cjs');
const root=path.resolve(__dirname,'..'),artifacts=path.join(__dirname,'offline-artifacts');fs.mkdirSync(artifacts,{recursive:true});
async function main(){const service=createService({root,directory:fs.mkdtempSync(path.join(artifacts,'academic-ui-'))});service.core.setup({name:'Dirección',username:'director',password:'Prueba2026!'});const d=service.core.users()[0];load(service.core,d,{year:'2026',institution:{nombre:'CETPRO prueba',codigoModular:'1027648'},calendar:[{name:'Periodo (2026-I)',start:'2026-03-16',end:'2026-07-24'},{name:'Periodo (2026-II)',start:'2026-08-10',end:'2026-12-18'}],personnel:[{year:'2026',name:'Persona',document:'00123456',position:'Docente',birthday:'28-Ene'}],programs:[{name:'Computación',turno:'Tarde',level:'Auxiliar Técnico',code:'',teacherNames:'Persona',modules:[1,2].map(index=>({index,nombre:'Módulo '+index,periodId:'2026-'+(index===1?'I':'II'),units:[{code:'UD1',name:'Ofimática',hours:336,credits:14},{code:'EFSRT',name:'Prácticas',hours:192,credits:6}]}))}]});const server=service.server();await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await puppeteer.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--no-sandbox','--disable-gpu'],userDataDir:fs.mkdtempSync(path.join(artifacts,'academic-browser-'))});const page=await browser.newPage(),errors=[];page.on('pageerror',err=>errors.push(err.message));await page.setViewport({width:1440,height:1000});await page.goto(`http://127.0.0.1:${server.address().port}`);await page.type('#username','director');await page.type('#password','Prueba2026!');await page.click('#login-form button[type=submit]');await page.waitForSelector('a[href="#/configuracion-academica"]');await page.click('a[href="#/configuracion-academica"]');await page.waitForSelector('#academic-form');assert.equal(await page.$eval('[data-field="institution.codigoModular"]',el=>el.value),'1027648');
 await page.$eval('[data-field="institution.nombre"]',el=>el.value='Nombre editado 2026');await page.click('#academic-form button[type=submit]');await page.waitForFunction(()=>document.querySelector('[data-field="institution.nombre"]')?.value==='Nombre editado 2026'&&document.querySelector('#toast')?.textContent.includes('guardada'),{polling:100});assert.equal(JSON.parse(service.core.record('documentSettings','academicYear:2026').fields.institutionJson).nombre,'Nombre editado 2026');
 await page.click('[data-tab="personnel"]');await page.waitForSelector('#personnel-new');await page.click('#personnel-new');await page.type('[data-field="name"]','Otra persona');await page.type('[data-field="document"]','00001122');await page.type('[data-field="position"]','Secretaria');await page.click('#academic-form button[type=submit]');await page.waitForFunction(()=>document.querySelector('#academic-record')?.value==='personnel:2026:00001122',{polling:100});assert.equal(service.core.record('documentSettings','personnel:2026:00001122').fields.position,'Secretaria');
 page.once('dialog',dialog=>dialog.accept('2027'));await page.click('#academic-new-year');await page.waitForFunction(()=>document.querySelector('#academic-year')?.value==='2027',{polling:100});assert.equal(service.core.record('documentSettings','academicPeriod:2027-I').fields.fechaInicio,'');await page.click('[data-tab="curriculum"]');await page.waitForSelector('[data-unit]');assert.equal(await page.$eval('[data-field="year"]',el=>el.value),'2027');await page.click('#unit-add');await page.type('[data-unit="UD2"] [data-field="name"]','Unidad nueva 2027');await page.type('[data-unit="UD2"] [data-field="hours"]','48');await page.type('[data-unit="UD2"] [data-field="credits"]','2');await page.click('#academic-form button[type=submit]');await page.waitForFunction(()=>document.querySelector('[data-unit="UD2"] summary')?.textContent.includes('Unidad nueva 2027'),{polling:100});assert.equal(service.core.records('documentSettings').filter(r=>r.scope.kind==='curriculum'&&r.fields.year==='2027').some(r=>JSON.parse(r.fields.unitsJson).some(u=>u.code==='UD2')),true);await page.screenshot({path:path.join(artifacts,'configuracion-academica.png')});
 await page.click('a[href="#/grupos"]');await page.waitForSelector('#new-group-form');await page.select('#new-group-program','PROG-2026-SOURCE-1');await page.select('#new-group-module','MOD-2026-SOURCE-1-1');await page.waitForFunction(()=>document.querySelector('#new-group-form [name="periodId"]')?.value==='2026-I',{polling:100});assert.equal(await page.$eval('#new-group-form [name="units"]',el=>el.value),'UD1, EFSRT');assert.deepEqual(errors,[]);console.log('Interfaz: edición institucional, alta de personal, año nuevo y sugerencias de grupos verificadas.');
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r));service.core.close();}}
main().catch(err=>{console.error(err);process.exitCode=1;});
