const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {OfflineCore}=require('../scripts/offline-core.cjs'),D=require('../scripts/offline-documents.cjs'),{renderPDF}=require('../scripts/offline-pdf.cjs');
const directory=path.join(__dirname,'offline-artifacts','dynamic');fs.mkdirSync(directory,{recursive:true});
test('códigos de prueba extensos en EFSRT se muestran completos en varias líneas sin bajar de 4 puntos',async()=>{const f=fixture();try{const s=f.c.record('students',f.enrollment.studentId);f.c.saveStudent(f.director,{...s,document:'PRUEBA-ALUMNO-02',rev:s.rev});const doc=f.c.document(f.director,{templateId:'TMPL-18',groupId:f.group.id}),auditFile=path.join(directory,'codigo-extenso.audit.json');const bytes=await renderPDF(path.resolve(__dirname,'..'),doc,f.director,{auditFile});fs.writeFileSync(path.join(directory,'codigo-extenso.pdf'),bytes);const measured=JSON.parse(fs.readFileSync(auditFile)).fields.find(f=>f.field==='student.0.code');assert.equal(measured.text,'MAT-PRUEBA-ALUMNO-02-001');assert.ok(measured.lines>1);assert.ok(measured.fontSize>=4);assert.equal(measured.fits,true);const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs'),pdf=await pdfjs.getDocument({data:new Uint8Array(bytes),disableFontFace:true,useSystemFonts:true}).promise;const text=(await(await pdf.getPage(1)).getTextContent()).items.map(i=>i.str).join('').replace(/\s/g,'');assert.ok(text.includes(measured.text));}finally{f.c.close();}});
function fixture(){const c=new OfflineCore(fs.mkdtempSync(path.join(directory,'db-')));c.setup({username:'director',name:'Dirección de ensayo',password:'password-test-123',institutionName:'CETPRO DE ENSAYO'});const director=c.users()[0],p=c.records('programs').find(p=>p.id==='PROG-005'),m=c.records('modules').find(m=>m.id==='MOD-009');
 const group=c.saveGroup(director,{name:'Grupo de ensayo',programId:p.id,moduleId:m.id,periodId:'2026-I',units:['UD1','UD2','UD3','UD4','UD5','UD6','UD7','EFSRT']});
 const student=c.saveStudent(director,{name:'Apellido Ensayo, Alumna',document:'PRUEBA-01',lastName1:'Apellido',lastName2:'Ensayo',firstNames:'Alumna',sex:'M',birthDate:'2000-01-02',documentType:'PRUEBA'});const enrollment=c.enroll(director,{studentId:student.id,groupId:group.id,startDate:'2026-03-01'});const teacher=c.saveUser(director,{username:'docente',name:'Docente de ensayo',password:'docente-test-123',role:'DOCENTE',assignments:[{groupId:group.id,units:group.units}]});const docente=c.user(teacher.id);
 const put=(kind,target,fields,unit)=>D.saveSettings(c,director,{scope:{kind,...(target?{target}:{}),...(unit?{unit}:{})},fields,rev:c.record('documentSettings',D.idFor({kind,target,unit}))?.rev||null});
 put('institution',null,{nombre:'CETPRO DE ENSAYO',tipoGestion:'PÚBLICA',codigoModular:'TEST001',dre:'DRE ENSAYO',ugel:'UGEL ENSAYO',region:'Región ensayo',departamento:'Departamento ensayo',provincia:'Provincia ensayo',distrito:'Distrito ensayo',lugar:'Lugar ensayo',direccion:'Dirección de ensayo',resolucionAutorizacion:'RES-TEST-001',resolucionConversion:'RES-TEST-002'});
 put('program',p.id,{nivelFormativo:'Nivel de ensayo',tipoPlan:'Plan de ensayo',resolucionPrograma:'RES-PROG-TEST',officialTitleText:'TÉCNICO DE ENSAYO'});
 put('module',m.id,{hours:210,credits:7,efsrtHours:30,competence:'Competencia confirmada de ensayo',resolucionAutorizacion:'RES-MOD-TEST',presenceStates:'P,T',absenceStates:'F,J',absenceDenominator:'PROGRAMADAS',approvalMinimum:13});
 put('group',group.id,{ciclo:'Ciclo de ensayo',seccion:'A',turno:'Mañana',modalidad:'Presencial',fechaInicio:'2026-03-01',fechaFin:'2026-07-31',periodClase:'Marzo - Julio',teacherName:'Docente de ensayo',efsrtInicio:'2026-04-01',efsrtFin:'2026-06-01'});
 for(const unit of group.units.filter(u=>u!=='EFSRT')){put('unit',group.id,{name:'Unidad de ensayo '+unit,capacity:'Opera herramientas del módulo',competence:'Competencia '+unit,...Object.fromEntries(Array.from({length:5},(_,i)=>['indicator'+(i+1),'Indicador de ensayo '+(i+1)]))},unit);put('unitCurriculum',group.id,{hours:30,credits:1},unit);
 c.saveAcademic(docente,'grades',{groupId:group.id,unit,rows:Array.from({length:5},(_,i)=>['IA1','IA2','IA3','','RECOVERY'].map(k=>({enrollmentId:enrollment.id,indicator:`IL${i+1}${k?'.'+k:''}`,value:k==='RECOVERY'?null:16.5,clear:k==='RECOVERY'}))).flat().concat([{enrollmentId:enrollment.id,indicator:'RESULTADO_UD',value:16.5}])});
 c.saveAcademic(docente,'attendance',{groupId:group.id,unit,date:'2026-03-02',session:'1',rows:[{enrollmentId:enrollment.id,value:'P'}]});}
 put('enrollment',enrollment.id,{condition:'G',emissionDate:'2026-07-31'});put('registry',enrollment.id,{registerCode:'REG-TEST-001',registryBook:'Libro de ensayo',registryFolio:'F01',registryNumber:'N01',registryDate:'2026-07-31',registryAsiento:'Asiento de ensayo'});
 put('practice',enrollment.id,{companyName:'EMPRESA DE ENSAYO',companyAddress:'DIRECCIÓN DE ENSAYO',...Object.fromEntries([3,2,2,3,3,3,1,2,1].map((v,i)=>['criterion'+(i+1),v])),efsrtFinalGrade:17});put('closure',enrollment.id,{modularGrade:16.5,approvedUnitsCount:7,failedUnitsCount:0,observations:'Datos de prueba'});
 return {c,director,docente,group,enrollment,put};}
test('21 documentos resuelven sus parámetros, fuentes y valores sin inventar campos faltantes',async()=>{const f=fixture();try{const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs');const coverage=[];for(let n=1;n<=21;n++){const templateId=`TMPL-${String(n).padStart(2,'0')}`,doc=f.c.document(f.director,{templateId,groupId:f.group.id,...([2,20,21].includes(n)?{enrollmentId:f.enrollment.id}:{})});assert.equal(doc.preflight.complete,true,templateId+': '+JSON.stringify(doc.preflight.missing));const bytes=await renderPDF(path.resolve(__dirname,'..'),doc,f.director);fs.writeFileSync(path.join(directory,`${templateId}.pdf`),bytes);const pdf=await pdfjs.getDocument({data:new Uint8Array(bytes),disableFontFace:true,useSystemFonts:true}).promise;let text='';for(let p=1;p<=pdf.numPages;p++)text+=(await(await pdf.getPage(p)).getTextContent()).items.map(i=>i.str).join(' ');
 assert.doesNotMatch(text,/BORRADOR|DEMOSTRACIÓN —/,templateId);if(n===1){assert.match(text,/RES-TEST-001/);assert.match(text,/RES-TEST-002/);assert.match(text,/Región ensayo/);assert.match(text,/Provincia ensayo/);}if(n===3){assert.match(text,/RES-PROG-TEST/);assert.match(text,/PRUEBA/);}if(n>=11&&n<=17)assert.match(text,/16\.5/,templateId+' debe conservar decimales');if(n===2){assert.match(text,/Unidad de ensayo UD1/);assert.match(text,/2026-I/);assert.match(text,/Ofimática/);}if(n===18){assert.match(text,/EMPRESA DE ENSAYO/);assert.match(text,/17/);}if(n===19){assert.match(text,/RES-MOD-TEST/);assert.match(text,/16\.5/);}if(n===20){assert.match(text,/REG-TEST-001/);assert.match(text,/Unidad de ensayo UD1/);assert.match(text,/F01/);}if(n===21){assert.match(text,/TÉCNICO DE ENSAYO/);assert.match(text,/Asiento de ensayo/);}coverage.push({templateId,parameters:doc.preflight.total,filled:doc.preflight.filled,complete:true,pages:pdf.numPages});}
 fs.writeFileSync(path.join(directory,'coverage.json'),JSON.stringify(coverage,null,2));}finally{f.c.close();}});
test('datos institucionales y registrales protegidos; docente solo configura sus unidades',()=>{const f=fixture();try{assert.throws(()=>D.saveSettings(f.c,f.docente,{scope:{kind:'institution'},fields:{nombre:'Alterado'}}),/configura dirección/);assert.throws(()=>D.saveSettings(f.c,f.docente,{scope:{kind:'unitCurriculum',target:f.group.id,unit:'UD1'},fields:{credits:10}}),/configura dirección/);assert.throws(()=>D.saveSettings(f.c,f.docente,{scope:{kind:'registry',target:f.enrollment.id},fields:{registerCode:'Otro'}}),/configura dirección/);const config=f.c.record('documentSettings',`unit:${f.group.id}:UD1`);D.saveSettings(f.c,f.docente,{scope:config.scope,fields:{indicator1:'Indicador actualizado'},rev:config.rev});assert.equal(f.c.document(f.docente,{templateId:'TMPL-11',groupId:f.group.id}).unitData.indicator1,'Indicador actualizado');}finally{f.c.close();}});
test('entrega conserva PDF exacto, revisión y evidencia; campos faltantes bloquean entrega',async()=>{const f=fixture();try{const input={templateId:'TMPL-11',groupId:f.group.id},doc=f.c.document(f.docente,input),bytes=await renderPDF(path.resolve(__dirname,'..'),doc,f.docente),submission=f.c.submitDocument(f.docente,doc,bytes);assert.deepEqual(f.c.submissionPDF(f.director,submission.id),bytes);assert.throws(()=>f.c.reviewDocument(f.docente,{id:submission.id,status:'REVISADO',reason:'Otro',rev:submission.rev}),/función/);const review=f.c.reviewDocument(f.director,{id:submission.id,status:'REVISADO',reason:'Verificado con plantilla',rev:submission.rev});assert.equal(review.status,'REVISADO');assert.deepEqual(f.c.submissionPDF(f.docente,submission.id),bytes);const setting=f.c.record('documentSettings',`unit:${f.group.id}:UD1`);D.saveSettings(f.c,f.docente,{scope:setting.scope,fields:{indicator1:''},rev:setting.rev});const incomplete=f.c.document(f.docente,input);assert.equal(incomplete.preflight.complete,false);assert.throws(()=>f.c.submitDocument(f.docente,incomplete,bytes),/parámetros pendientes/);}finally{f.c.close();}});
test('configuración y entregas se sincronizan cifradas hacia el equipo asignado sin datos de otros grupos',async()=>{const f=fixture(),target=new OfflineCore(fs.mkdtempSync(path.join(directory,'remote-')));try{const invitation=f.c.provision(f.director,{userId:f.docente.id,request:target.requestDevice()});target.acceptProvision({package:invitation,fingerprint:invitation.fingerprint});const actor=target.user(f.docente.id);target.importPackage(actor,f.c.packageFor(f.director,target.status().deviceId),true);assert.equal(target.document(actor,{templateId:'TMPL-11',groupId:f.group.id}).preflight.complete,true);const unit=target.record('documentSettings',`unit:${f.group.id}:UD1`);D.saveSettings(target,actor,{scope:unit.scope,rev:unit.rev,fields:{indicator1:'Indicador enviado por docente'}});f.c.importPackage(f.director,target.packageFor(actor),true);assert.equal(f.c.document(f.director,{templateId:'TMPL-11',groupId:f.group.id}).unitData.indicator1,'Indicador enviado por docente');const doc=target.document(actor,{templateId:'TMPL-11',groupId:f.group.id});const bytes=await renderPDF(path.resolve(__dirname,'..'),doc,actor);const submission=target.submitDocument(actor,doc,bytes);f.c.importPackage(f.director,target.packageFor(actor),true);assert.deepEqual(f.c.submissionPDF(f.director,submission.id),bytes);f.c.reviewDocument(f.director,{id:submission.id,rev:f.c.record('documentSubmissions',submission.id).rev,status:'REVISADO',reason:'Recibido por USB'});target.importPackage(actor,f.c.packageFor(f.director,target.status().deviceId),true);assert.equal(target.record('documentSubmissions',submission.id).status,'REVISADO');}finally{target.close();f.c.close();}});
test('nombres de módulo extensos se imprimen completos dentro de la celda sin abreviar',async()=>{const f=fixture();try{const longName=f.c.records('modules').find(m=>m.id==='MOD-003').nombre,mod=f.c.record('modules',f.group.moduleId);f.c.putRecord('modules',{...mod,nombre:longName,nombreOficial:longName});const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs');for(const templateId of ['TMPL-02','TMPL-03','TMPL-04']){const doc=f.c.document(f.director,{templateId,groupId:f.group.id,...(templateId==='TMPL-02'?{enrollmentId:f.enrollment.id}:{})});const bytes=await renderPDF(path.resolve(__dirname,'..'),doc,f.director),pdf=await pdfjs.getDocument({data:new Uint8Array(bytes),disableFontFace:true,useSystemFonts:true}).promise;const text=(await(await pdf.getPage(1)).getTextContent()).items.map(i=>i.str).join(' ').replace(/\s+/g,' ');assert.ok(text.includes(longName),templateId+': conserva el nombre completo del módulo');}}finally{f.c.close();}});
