const {fixture}=require('./helpers/official-fixture.cjs'),{configure}=require('../scripts/configure-official-2026.cjs'),{createService}=require('../scripts/offline-http.cjs');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),puppeteer=require('puppeteer');
async function main(){const f=fixture();configure(f.c,f.d);const directory=f.c.directory;f.c.close();const root=path.resolve(__dirname,'..'),artifacts=path.join(__dirname,'offline-artifacts'),service=createService({root,directory}),server=service.server();await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
 try{browser=await puppeteer.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--no-sandbox','--disable-gpu'],userDataDir:fs.mkdtempSync(path.join(artifacts,'official-ui-browser-'))});const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewport({width:1440,height:1000});await page.goto(`http://127.0.0.1:${server.address().port}`);
 const login=async(user,password)=>{await page.waitForSelector('#username');await page.type('#username',user);await page.type('#password',password);await page.locator('#login-form button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#logout')||document.querySelector('[data-module]'),{polling:100});if(await page.$('[data-module]')){await page.locator('[data-module]').click();await page.waitForSelector('[data-unit]');await page.locator('[data-unit]:not([data-unit="EFSRT"])').click();}await page.waitForSelector('#logout');};
 await login('director','Director2026!');await page.locator('a[href="#/matriculas"]').click();await page.waitForSelector('#module-filter');await page.select('#module-filter','GRP-BD-001');assert.equal(await page.$$eval('#module-rows tr',rs=>rs.length),1);page.once('dialog',d=>d.accept('No pertenece al módulo I'));await page.locator('[data-module-action="EXCLUDE"][data-id="EN-0-0"]').click();await page.waitForSelector('[data-module-action="RESTORE"][data-id="EN-0-0"]');assert.equal(service.core.record('enrollments','EN-0-0').active,false);assert.equal(service.core.records('enrollments').find(r=>r.groupId==='GRP-BD-001-M2').active,true);
 page.once('dialog',d=>d.accept('Corregido'));await page.locator('[data-module-action="RESTORE"][data-id="EN-0-0"]').click();await page.waitForSelector('[data-module-action="CONFIRM"][data-id="EN-0-0"]');page.once('dialog',d=>d.accept('Lista revisada'));await page.locator('[data-module-action="CONFIRM"][data-id="EN-0-0"]').click();await page.waitForFunction(()=>!document.querySelector('[data-module-action="CONFIRM"][data-id="EN-0-0"]'),{polling:100});assert.equal(service.core.record('enrollments','EN-0-0').provisional,false);await page.screenshot({path:path.join(artifacts,'matriculas-por-modulo.png')});
 await page.locator('a[href="#/cuentas"]').click();await page.waitForSelector('#account-form');const pending=service.core.users().find(u=>u.username==='magda.chura');await page.locator(`[data-user="${pending.id}"]`).click();assert.equal(await page.$eval('[name="assignmentPending"]',el=>el.checked),true);await page.locator('#account-form button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#toast')?.textContent.includes('Cuenta guardada'),{polling:100});assert.equal(service.core.user(pending.id).assignments.length,0);
 await page.locator('#account-menu summary').click();await page.locator('#logout').click();await login('magda.chura','Magda2026!');assert.equal(await page.$('a[href="#/matriculas"]'),null);assert.equal(await page.$('a[href="#/configuracion-academica"]'),null);await page.locator('a[href="#/estudiantes"]').click();await page.waitForSelector('#student-rows');assert.equal(await page.$eval('#student-rows',el=>el.textContent.includes('Alumno')),false);
 await page.locator('#account-menu summary').click();await page.locator('#logout').click();await login('alejandrina.ayna','Alejandrina2026!');await page.locator('a[href="#/documentos"]').click();await page.waitForSelector('#document-template');assert.equal(await page.$$eval('#document-group option',els=>els.filter(e=>e.value).length),1);await page.select('#document-template','TMPL-05');await page.locator('#document-generate').click();await page.waitForFunction(()=>document.querySelector('.pdf-canvas')?.width>0&&!document.querySelector('#document-pdf')?.disabled,{polling:100,timeout:60000});assert.deepEqual(errors,[]);console.log('Interfaz: confirmar/quitar/restaurar módulo, cuenta pendiente sin acceso y asistencia docente con PDF verificadas.');
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r));service.core.close();}}
main().catch(e=>{console.error(e);process.exitCode=1;});
