const {unitFixture}=require('./helpers/unit-fixture.cjs'),{createService}=require('../scripts/offline-http.cjs'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),puppeteer=require('puppeteer');
async function main(){const f=unitFixture(),directory=f.c.directory;f.c.close();const root=path.resolve(__dirname,'..'),service=createService({root,directory}),server=service.server();await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{browser=await puppeteer.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--no-sandbox','--disable-gpu'],userDataDir:fs.mkdtempSync(path.join(__dirname,'offline-artifacts/guided-browser-'))});const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewport({width:1440,height:1000});await page.goto(`http://127.0.0.1:${server.address().port}`);await page.type('#username','alejandrina.ayna');await page.type('#password','Alejandrina2026!');await page.locator('#login-form button[type=submit]').click();await page.waitForSelector('[data-module]');await page.locator('[data-module="MOD-2026-AFICHE-004-1"]').click();await page.waitForSelector('[data-unit="UD2"]');await page.locator('[data-unit="UD2"]').click();await page.waitForSelector('.unit-guide');await page.locator('.unit-guide a[href="#/evaluacion"]').click();await page.waitForSelector('[data-grade-tab]');await page.waitForFunction(()=>document.querySelector('.matrix-score'));
assert.equal(await page.$$eval('.matrix-score',els=>els.filter(e=>e.getClientRects().length).length),5);
await page.$eval('[data-indicator="IL1.IA1"]',el=>{el.value='0';el.dispatchEvent(new Event('input',{bubbles:true}));});await page.locator('[data-grade-tab="2"]').click();await page.$eval('[data-indicator="IL2.IA1"]',el=>{el.value='17';el.dispatchEvent(new Event('input',{bubbles:true}));});await page.locator('[data-grade-tab="6"]').click();assert.equal(await page.$$eval('.matrix-score',els=>els.filter(e=>e.getClientRects().length).length),1);await page.$eval('[data-indicator="RESULTADO_UD"]',el=>{el.value='16';el.dispatchEvent(new Event('input',{bubbles:true}));});await page.locator('#save-academic').click();await page.waitForFunction(()=>document.querySelector('#save-state').textContent.includes('Guardado'));
const grades=service.core.records('grades');assert.equal(grades.find(r=>r.unit==='UD2'&&r.indicator==='IL1.IA1').value,0);assert.equal(grades.find(r=>r.unit==='UD2'&&r.indicator==='IL2.IA1').value,17);assert.equal(grades.find(r=>r.unit==='UD1').value,12);assert.equal(grades.find(r=>r.unit==='UD2'&&r.indicator==='IL1').value,18);
await page.screenshot({path:path.join(__dirname,'offline-artifacts/evaluacion-guiada.png')});await page.locator('.unit-guide a[href="#/asistencia"]').click();await page.waitForSelector('#attendance-document');await page.locator('#attendance-document').click();await page.waitForSelector('#document-template');assert.equal(await page.$eval('#document-template',e=>e.value),'TMPL-06');assert.equal(await page.$eval('.document-advanced',e=>e.open),false);assert.deepEqual(errors,[]);console.log('Guía docente: cambios entre indicadores, cero válido, guardado conjunto, aislamiento UD1/UD2 y ficha correcta desde asistencia.');
}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));service.core.close();}}
main().catch(e=>{console.error(e);process.exitCode=1;});
