const {fixture}=require('./helpers/official-fixture.cjs'),{configure}=require('../scripts/configure-official-2026.cjs'),{seed}=require('../scripts/zip-defaults-2026.cjs'),{createService}=require('../scripts/offline-http.cjs');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),puppeteer=require('puppeteer');
async function main(){const f=fixture();configure(f.c,f.d);seed(f.c,f.d);const directory=f.c.directory;f.c.close();const root=path.resolve(__dirname,'..'),artifacts=path.join(__dirname,'offline-artifacts'),service=createService({root,directory}),server=service.server();await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
 try{browser=await puppeteer.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--no-sandbox','--disable-gpu'],userDataDir:fs.mkdtempSync(path.join(artifacts,'workspace-browser-'))});const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewport({width:1440,height:1000});await page.goto(`http://127.0.0.1:${server.address().port}`);const login=async(u,p)=>{await page.waitForSelector('#username');await page.type('#username',u);await page.type('#password',p);await page.click('#login-form button[type=submit]');};
 await login('alejandrina.ayna','Alejandrina2026!');await page.waitForSelector('[data-module]');assert.equal(await page.$$eval('[data-module]',rows=>rows.length),2);await page.screenshot({path:path.join(artifacts,'seleccion-modulos.png')});await page.click('[data-module="MOD-2026-AFICHE-004-1"]');await page.waitForSelector('[data-unit="UD1"]');await page.locator('[data-unit="UD1"]').click();await page.waitForSelector('#workspace-change');assert.ok(await page.$eval('#workspace-banner',el=>el.textContent.includes('2026-I')));await page.click('a[href="#/documentos"]');await page.waitForSelector('#document-group');assert.deepEqual(await page.$$eval('#document-group option',rows=>rows.map(r=>r.value)),['GRP-BD-001']);await page.click('#workspace-change');await page.waitForSelector('[data-module]');await page.click('[data-module="MOD-2026-AFICHE-004-2"]');await page.waitForSelector('[data-unit="UD1"]');await page.locator('[data-unit="UD1"]').click();await page.waitForSelector('#workspace-change');await page.click('a[href="#/documentos"]');await page.waitForSelector('#document-group');assert.deepEqual(await page.$$eval('#document-group option',rows=>rows.map(r=>r.value)),['GRP-BD-001-M2']);await page.screenshot({path:path.join(artifacts,'modulo-ii-documentos.png')});
 await page.click('#account-menu summary');await page.click('#logout');await login('director','Director2026!');await page.waitForSelector('#workspace-change');await page.click('a[href="#/configuracion-academica"]');await page.waitForSelector('[data-tab="moduleDefaults"]');await page.click('[data-tab="moduleDefaults"]');await page.waitForSelector('#reference-module');assert.ok(await page.$('[data-field="source"]'));assert.ok(await page.$('[data-field="notes"]'));await page.screenshot({path:path.join(artifacts,'referencias-zip.png')});
 await page.click('#workspace-change');await page.waitForSelector('#workspace-program');await page.select('#workspace-program','PROG-005');await page.click('[data-module="MOD-2026-AFICHE-005-1"]');await page.waitForSelector('[data-aula]');assert.equal(await page.$$eval('[data-aula]',rows=>rows.length),2);await page.click('[data-aula="GRP-BD-008"]');await page.waitForSelector('[data-module-space]');await page.locator('[data-module-space]').click();await page.waitForSelector('#workspace-change');assert.ok(await page.$eval('#workspace-banner',el=>el.textContent.includes('VIRTUAL')));await page.click('#workspace-change');await page.waitForSelector('#workspace-overview');await page.click('#workspace-overview');await page.waitForSelector('#workspace-change');assert.equal(await page.$eval('#workspace-banner',el=>el.textContent),'Vista general de la institución');
 await page.setViewport({width:390,height:844});await page.click('#workspace-change');await page.waitForSelector('#workspace-program');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await page.screenshot({path:path.join(artifacts,'seleccion-modulos-movil.png')});assert.deepEqual(errors,[]);console.log('Interfaz: selección obligatoria docente, cambio de módulo, aulas por modalidad, referencias ZIP y móvil verificados.');
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r));service.core.close();}}
main().catch(e=>{console.error(e);process.exitCode=1;});
