export async function applyCurriculumSuggestions(page,{api}){
 const config=await api('academic/configuration');if(!page.isConnected)return;
 const curricula=config.records.filter(r=>r.scope.kind==='curriculum');
 const bind=form=>{const select=form.elements.moduleId;if(!select)return;select.addEventListener('change',()=>{const f=curricula.find(r=>r.scope.target===select.value)?.fields;if(!f)return;form.elements.periodId.value=f.periodId;form.elements.units.value=JSON.parse(f.unitsJson).map(u=>u.code).join(', ');if(!form.elements.turno.value)form.elements.turno.value=f.turno||'';});};
 page.querySelectorAll('.group-form,#new-group-form').forEach(bind);
}
export async function renderAcademicConfig(page,ctx,initial={}){
 const {api,escape:e,heading,notice}=ctx,config=await api('academic/configuration'),records=config.records;
 const years=records.filter(r=>r.scope.kind==='academicYear').sort((a,b)=>b.scope.target.localeCompare(a.scope.target));let year=initial.year||years[0]?.scope.target||'',tab=initial.tab||'academicYear',selected=initial.selected||'',formDirty=false;
 const canSwitch=()=>{if(formDirty&&!confirm('Hay cambios sin guardar. ¿Cambiar y descartar esos cambios?'))return false;formDirty=false;ctx.setDirty?.(false);return true;};
 const labels={academicYear:'Institución y calendario',academicPeriod:'Periodos',curriculum:'Programas y módulos',moduleDefaults:'Valores iniciales',personnel:'Directorio del personal'};
 const input=(key,label,value,type='text')=>['notes','sourceNote','competence','capacity'].includes(key)?`<label>${e(label)}<textarea data-field="${e(key)}" placeholder="Escriba el dato de referencia"${!config.editable?' disabled':''}>${e(value??'')}</textarea></label>`:`<label>${e(label)}<input data-field="${e(key)}" type="${type}" value="${e(value??'')}" ${type==='number'?'min="0" step="any"':''} placeholder="${type==='date'?'AAAA-MM-DD':type==='number'?'Ej.: 48':key==='document'?'Ej.: 01309890':key==='birthday'?'Ej.: 28-Ene (año desconocido)':'Ej.: '+e(label)}"${!config.editable?' disabled':''}></label>`;
 const parse=v=>JSON.parse(v||'[]');
 function draw(){const list=records.filter(r=>r.scope.kind===tab&&(tab==='academicYear'?r.scope.target===year:r.fields.year===year));const row=list.find(r=>r.id===selected)||list[0];selected=row?.id||'';const f=row?.fields||{};
 page.innerHTML=heading('Configuración por año','Datos reales, editables y separados por periodo. El directorio no crea cuentas ni asigna aulas automáticamente.')+`<div class="card toolbar"><label>Año lectivo<select id="academic-year">${years.map(r=>`<option ${r.scope.target===year?'selected':''}>${e(r.scope.target)}</option>`).join('')}</select></label>${config.editable?'<button id="academic-new-year">Preparar otro año</button>':''}</div><div class="subnav">${Object.entries(labels).map(([key,label])=>`<button data-tab="${key}" ${tab===key?'class="primary"':''}>${label}</button>`).join('')}</div><div class="card"><h2>${labels[tab]}</h2>${tab==='personnel'&&config.editable?'<button type="button" id="personnel-new">Registrar otra persona</button>':''}${list.length>1?`<label>Registro<select id="academic-record">${list.map(r=>`<option value="${e(r.id)}" ${r.id===selected?'selected':''}>${e(r.fields.name||[r.fields.programName,r.fields.nombre].filter(Boolean).join(' / ')||records.find(c=>c.scope.kind==='curriculum'&&c.scope.target===r.scope.target)?.fields.nombre||r.scope.target)}</option>`).join('')}</select></label>`:''}<form id="academic-form"><div class="form-grid" id="academic-fields"></div><div id="academic-tables"></div><p class="error" data-error></p>${row&&config.editable?'<button class="primary" type="submit">Guardar configuración de este año</button>':''}</form></div><details class="card"><summary>Pendientes de revisión (${(config.issues[year]||[]).length})</summary><p>Los valores se conservan como fueron entregados. Complete fechas, turnos y datos faltantes; confirme las diferencias antes de emitir documentos oficiales.</p>${(config.issues[year]||[]).map(s=>`<p>${e(s)}</p>`).join('')}</details><div class="card"><h2>Aulas y usuarios</h2><p>En Grupos seleccione el módulo del año, indique sección y turno y complete las unidades. Después, en Usuarios y asignaciones, cree la cuenta docente y seleccione sus aulas. Los grupos históricos pendientes conservan sus matrículas.</p><a class="button" href="#/grupos">Configurar grupos</a> <a class="button" href="#/cuentas">Usuarios y asignaciones</a></div>`;
 const fields=page.querySelector('#academic-fields'),tables=page.querySelector('#academic-tables');
 const ref=tab==='curriculum'&&row?records.find(r=>r.scope.kind==='moduleDefaults'&&r.scope.target===row.scope.target):null;if(ref){const box=document.createElement('section');box.className='card';box.innerHTML='<h3>Valores iniciales del módulo</h3><p>Revise estos datos antes de aplicarlos al plan. Puede corregirlos en Valores iniciales.</p>'+(config.editable?'<button id="reference-apply" type="button">Aplicar valores de referencia al plan</button>':'');page.querySelector('#academic-form').after(box);const button=box.querySelector('button');if(button)button.onclick=async()=>{if(!confirm('Esto actualizará los valores del plan con la referencia indicada. Revise las diferencias mostradas; se conservará una copia previa. ¿Aplicar?'))return;try{await api('academic/reference/apply',{moduleId:row.scope.target,rev:row.rev});notice('Referencia aplicada al plan.');await renderAcademicConfig(page,ctx,{year,tab,selected});}catch(err){notice(err.message,true);}};}
 if(row){if(tab==='academicYear'){
 const inst=JSON.parse(f.institutionJson||'{}');fields.innerHTML=Object.entries(inst).map(([k,v])=>input('institution.'+k,config.institutionSchema.find(f=>f.key===k)?.label||k,v)).join('')+input('hours','Horas anuales declaradas',f.hours,'number')+input('credits','Créditos anuales declarados',f.credits,'number')+input('directoryDate','Fecha del directorio',f.directoryDate,'date')+input('directoryPlace','Lugar del directorio',f.directoryPlace);
 tables.innerHTML='<h3>Calendarización</h3><p>Edite cada bloque. Los periodos de clases se configuran también en Periodos.</p><div id="calendar-rows">'+parse(f.calendarJson).map(c=>`<div class="form-grid" data-calendar>${config.editable?'<button type="button" data-remove-calendar>Quitar bloque</button>':''}${input('name','Bloque (ej.: Vacaciones)',c.name)}${input('start','Inicio',c.start,'date')}${input('end','Término',c.end,'date')}${input('detail','Detalle',c.detail)}</div>`).join('')+'</div>'+(config.editable?'<button type="button" id="calendar-add">Añadir bloque de calendario</button>':'');
 }else{fields.innerHTML=config.schema[tab].filter(s=>s.type!=='json'&&!['source','sourceNote','notes'].includes(s.key)).map(s=>input(s.key,s.label,f[s.key],s.type==='number'?'number':s.type==='date'?'date':'text')).join('');fields.querySelector('[data-field="year"]')?.setAttribute('readonly','');if(tab==='personnel'&&row.rev)fields.querySelector('[data-field="document"]')?.setAttribute('readonly','');
 if(tab==='curriculum'){tables.innerHTML='<h3>Unidades didácticas y EFSRT</h3><p>Las horas desconocidas se dejan vacías. Los nombres, horas, créditos y fechas se usan como base del llenado documental de las aulas que seleccionen este módulo.</p>'+parse(f.unitsJson).map(u=>`<details class="card" data-unit="${e(u.code)}"><summary>${e(u.code+' · '+u.name)}</summary><div class="form-grid">${input('name','Nombre de la unidad',u.name)}<label><input type="checkbox" data-field="confirmed" ${u.confirmed!==false?'checked':''}${!config.editable?' disabled':''}> Nombre, horas y créditos confirmados para este módulo</label>${['hours','credits','theoryHours','practiceHours','days'].map(k=>input(k,({hours:'Horas totales',credits:'Créditos',theoryHours:'Horas teóricas',practiceHours:'Horas prácticas',days:'Días declarados'})[k],u[k],'number')).join('')}${input('fechaInicio','Inicio',u.fechaInicio,'date')}${input('fechaFin','Término',u.fechaFin,'date')}</div>${config.editable&&u.code!=='EFSRT'?'<button type="button" data-remove-unit>Quitar unidad del plan</button>':''}</details>`).join('')+(config.editable?'<button id="unit-add" type="button">Añadir unidad didáctica</button>':'');}
 }}
 page.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{if(!canSwitch())return;tab=b.dataset.tab;selected='';draw();});page.querySelector('#academic-year').onchange=ev=>{if(!canSwitch()){ev.target.value=year;return;}year=ev.target.value;selected='';draw();};const select=page.querySelector('#academic-record');if(select)select.onchange=ev=>{if(!canSwitch()){ev.target.value=selected;return;}selected=ev.target.value;draw();};const add=page.querySelector('#calendar-add');if(add)add.onclick=()=>page.querySelector('#calendar-rows').insertAdjacentHTML('beforeend',`<div class="form-grid" data-calendar>${input('name','Bloque (ej.: Gestión)', '')}${input('start','Inicio','','date')}${input('end','Término','','date')}${input('detail','Detalle','')}</div>`);
 tables.addEventListener('click',ev=>{if(ev.target.matches('[data-remove-unit]'))ev.target.closest('[data-unit]').remove();if(ev.target.matches('[data-remove-calendar]'))ev.target.closest('[data-calendar]').remove();});const addUnit=page.querySelector('#unit-add');if(addUnit)addUnit.onclick=()=>{const used=[...page.querySelectorAll('[data-unit]')].map(el=>el.dataset.unit),code=Array.from({length:7},(_,i)=>'UD'+(i+1)).find(c=>!used.includes(c));if(!code){notice('Los formatos disponibles admiten hasta siete unidades didácticas.',true);return;}addUnit.insertAdjacentHTML('beforebegin',`<details class="card" data-unit="${code}" open><summary>${code} · Unidad nueva</summary><div class="form-grid">${input('name','Nombre de la unidad','')}${input('hours','Horas totales','','number')}${input('credits','Créditos','','number')}${input('fechaInicio','Inicio','','date')}${input('fechaFin','Término','','date')}</div><button type="button" data-remove-unit>Quitar unidad del plan</button></details>`);};
 if(row&&tab==='moduleDefaults'){const reference=JSON.parse(f.dataJson||'{"module":{},"units":[]}');tables.innerHTML='<h3>Valores de referencia</h3><p>Se usan cuando falta un dato. Las modificaciones guardadas en el plan o aula tienen prioridad. Revise los datos y complete los campos pendientes.</p><div id="reference-module" class="form-grid">'+Object.entries(reference.module).map(([k,v])=>input(k,({hours:'Horas del módulo',credits:'Créditos del módulo',efsrtHours:'Horas EFSRT',competence:'Unidad de competencia'})[k]||k,v,typeof v==='number'?'number':'text')).join('')+'</div>'+reference.units.map(u=>'<details class="card" data-reference-unit="'+e(u.code)+'"><summary>'+e(u.code+' · '+u.name)+'</summary><div class="form-grid">'+Object.entries(u).filter(([k])=>!['code','dateOrigin','nameOrigin'].includes(k)).map(([k,v])=>input(k,({name:'Nombre de la unidad',hours:'Horas',credits:'Créditos',capacity:'Capacidad',fechaInicio:'Inicio',fechaFin:'Término',days:'Días declarados',theoryHours:'Horas teóricas',practiceHours:'Horas prácticas'})[k]||k,v,['hours','credits','theoryHours','practiceHours','days'].includes(k)?'number':k.startsWith('fecha')?'date':'text')).join('')+'</div></details>').join('');}
 const newPerson=page.querySelector('#personnel-new');if(newPerson)newPerson.onclick=()=>{if(!canSwitch())return;const draft={id:'draft-person',scope:{kind:'personnel',target:''},fields:{year}};const old=records.findIndex(r=>r.id===draft.id);if(old>=0)records.splice(old,1);records.push(draft);selected=draft.id;draw();};
 const newYear=page.querySelector('#academic-new-year');if(newYear)newYear.onclick=async()=>{if(!canSwitch())return;const next=prompt('Año que desea preparar (ej.: 2027). Se copiará el plan; las fechas, aulas y asignaciones deberán confirmarse.');if(!next)return;try{await api('academic/year',{sourceYear:year,year:next.trim()});notice('Año creado. Complete fechas y revise docentes y módulos.');await renderAcademicConfig(page,ctx);}catch(err){notice(err.message,true);}};
 page.querySelector('#academic-form').oninput=()=>{formDirty=true;ctx.setDirty?.(true);};page.querySelector('#academic-form').onsubmit=async ev=>{ev.preventDefault();if(!row||!config.editable)return;try{const values={...f};const read=box=>Object.fromEntries([...box.querySelectorAll('[data-field]')].map(el=>[el.dataset.field,el.type==='checkbox'?el.checked:el.type==='number'?(el.value===''?null:Number(el.value)):el.value]));Object.assign(values,read(fields));if(tab==='academicYear'){const inst={};for(const k of Object.keys(values))if(k.startsWith('institution.')){inst[k.slice(12)]=values[k];delete values[k];}values.institutionJson=JSON.stringify(inst);values.calendarJson=JSON.stringify([...page.querySelectorAll('[data-calendar]')].map(read));}if(tab==='moduleDefaults'){values.dataJson=JSON.stringify({module:read(page.querySelector('#reference-module')),units:[...page.querySelectorAll('[data-reference-unit]')].map(box=>({...parse(f.dataJson).units.find(u=>u.code===box.dataset.referenceUnit),code:box.dataset.referenceUnit,...read(box)}))});}if(tab==='curriculum')values.unitsJson=JSON.stringify([...page.querySelectorAll('[data-unit]')].map(box=>({...parse(f.unitsJson).find(u=>u.code===box.dataset.unit),code:box.dataset.unit,...read(box)})));const saved=await api('document/configuration',{scope:tab==='personnel'&&!row.rev?{kind:'personnel',target:year+':'+values.document}:row.scope,fields:values,rev:row.rev||null});formDirty=false;ctx.setDirty?.(false);notice('Configuración guardada. Los registros de otros años se conservan.');await renderAcademicConfig(page,ctx,{year,tab,selected:saved.id});}catch(err){page.querySelector('[data-error]').textContent=err.message;}};
 }
 draw();
}
