import {configureTeacherAssignments} from './teacher-assignments.js';
import {renderPortableExchange} from './exchange.js';
import {renderDataExchange}from'./data-exchange.js';
import { renderDocuments, renderDocumentConfiguration, renderDeliveries } from './documents.js';
import { renderGradeMatrix } from './grade-matrix.js';
const root = document.querySelector('#app');
const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
let token = sessionStorage.getItem('CETPRO_LOCAL_TOKEN'), data, routeVersion = 0, dirty = false, currentPackage = null;
const roleName = { DIRECTOR: 'Dirección', SECRETARIA: 'Secretaría académica', DOCENTE: 'Docente' };
const today = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Lima', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
const notice = (message, error = false) => { const toast = document.querySelector('#toast'); toast.textContent = message; toast.className = `visible${error ? ' error' : ''}`; clearTimeout(notice.timer); notice.timer = setTimeout(() => toast.className = '', 7000); };
async function api(endpoint, payload) {
  const response = await fetch(`/api/${endpoint}`, { method: payload === undefined ? 'GET' : 'POST', headers: { ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(payload === undefined ? {} : { 'Content-Type': 'application/json' }) }, ...(payload === undefined ? {} : { body: JSON.stringify(payload) }) });
  if (response.ok && response.headers.get('content-type')?.includes('application/pdf')) return response.blob();
  const result = await response.json(); if (!response.ok) { if (response.status === 401 && endpoint !== 'login') { token = null; sessionStorage.removeItem('CETPRO_LOCAL_TOKEN'); } throw new Error(result.error); } return result;
}
function download(value, name) { const url = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
const options = (values, selected, label = v => v.name || v.nombre || v.id) => values.map(v => `<option value="${escape(v.id)}"${v.id === selected ? ' selected' : ''}>${escape(label(v))}</option>`).join('');
function formValues(form) { return Object.fromEntries(new FormData(form)); }
function bindForm(selector, handler) {
  const form = document.querySelector(selector); if (!form) return;
  form.addEventListener('submit', async event => { event.preventDefault(); const button = form.querySelector('[type=submit]'); if (button) button.disabled = true;
    try { await handler(formValues(form), form); } catch (e) { notice(e.message, true); const error = form.querySelector('[data-error]'); if (error) error.textContent = e.message; }
    finally { if (button?.isConnected) button.disabled = false; }
  });
}
async function readJSON(file) { if (!file || file.size > 32 * 1024 * 1024) throw new Error('Seleccione un archivo JSON de hasta 32 MB.'); return JSON.parse(await file.text()); }
const heading = (title, subtitle, action = '') => `<div class="page-head"><div><div class="eyebrow">GESTIÓN ACADÉMICA</div><h1>${title}</h1><p>${subtitle}</p></div>${action}</div>`;
const studentName = enrollment => data.students.find(s => s.id === enrollment.studentId)?.name || 'Estudiante pendiente de sincronizar';
const groupLabel = group => group.name || group.id;
const authBrand = `<section class="auth-brand"><img src="/app/img/logo-cetpro.jpg" alt="Emblema del CETPRO"><div class="eyebrow">CETPRO PÚBLICO</div><h1>Tu trabajo académico,<br>en un solo lugar.</h1><p>Matrículas, notas y asistencia con acceso individual y sincronización segura entre equipos.</p><p>● Funciona sin internet</p></section>`;

async function authScreen() {
  const status = await api('status');
  if (!status.initialized) {
    root.innerHTML = `<div class="auth">${authBrand}<section class="auth-form"><h1>Configurar este equipo</h1><p class="muted">El equipo institucional administra las cuentas. Los demás equipos se vinculan mediante USB.</p><details open><summary><strong>Crear el equipo institucional</strong></summary><form id="setup-form"><label>Nombre de la institución<input name="institutionName" value="CETPRO Micaela Bastidas" required></label><label>Nombre del director<input name="name" required autocomplete="name"></label><label>Usuario de dirección<input name="username" required autocomplete="username" pattern="[a-zA-Z0-9._-]{3,60}"></label><label>Contraseña<input name="password" type="password" minlength="8" required autocomplete="new-password"></label><label class="login-check"><input name="importBaseline" type="checkbox"${status.baselineAvailable ? ' checked' : ' disabled'}> Incorporar el respaldo institucional existente</label><p class="error" data-error></p><button class="primary" type="submit">Crear dirección e iniciar</button></form></details><div class="divider"></div><details><summary><strong>Vincular con una institución existente</strong></summary><p>1. Exporte la solicitud y entréguela a dirección.</p><button id="device-request">Descargar solicitud de este equipo</button><p>2. Importe el archivo de vinculación entregado por dirección.</p><form id="link-form"><label>Archivo de vinculación<input name="file" type="file" accept=".cetpro,.json" required></label><label>Huella institucional confirmada con dirección<input name="fingerprint" required placeholder="64 caracteres de la huella SHA-256"></label><p class="error" data-error></p><button type="submit" class="primary">Verificar y vincular</button></form></details></section></div>`;
    bindForm('#setup-form', async values => { await api('setup', { ...values, importBaseline: values.importBaseline === 'on' }); notice('Dirección creada. Ingrese con su usuario y contraseña.'); await authScreen(); });
    document.querySelector('#device-request').onclick = async () => { try { download(await api('device-request'), 'SOLICITUD_EQUIPO.cetpro'); } catch (e) { notice(e.message, true); } };
    bindForm('#link-form', async (values, form) => { await api('provision/accept', { package: await readJSON(form.elements.file.files[0]), fingerprint: values.fingerprint.trim() }); notice('Equipo vinculado. Ingrese con su cuenta.'); await authScreen(); });
    return;
  }
  root.innerHTML = `<div class="auth">${authBrand}<section class="auth-form"><button id="login-theme" class="small" type="button">Cambiar claro / oscuro</button><div class="eyebrow">ACCESO PERSONAL</div><h1>Bienvenido a tu CETPRO</h1><p class="muted">${escape(status.institutionName)}<br>Ingresa con la cuenta asignada por dirección.</p><form id="login-form"><label>Usuario<input name="username" id="username" required autocomplete="username" autofocus placeholder="Tu nombre de usuario"></label><label>Contraseña<div class="password-row"><input name="password" id="password" type="password" required autocomplete="current-password" placeholder="Tu contraseña"><button type="button" id="show-password" aria-label="Mostrar contraseña">Mostrar</button></div></label><p class="error" data-error aria-live="polite"></p><button type="submit" class="primary">Ingresar al sistema →</button></form><div class="divider"></div><p class="muted">Tu rol y tus aulas se cargan desde tu cuenta.<br>Si necesitas recuperar el acceso, acude a dirección.</p><span class="badge">Operación local · Datos guardados en este equipo</span>${!status.authority ? `<details><summary>Recibir actualización institucional de acceso (.cetpro)</summary><p>Dirección exporta un archivo seleccionando tu cuenta. Permite recibir la nueva contraseña, autorización o restauración.</p><form id="recover-exchange-form"><label>Archivo institucional<input name="file" type="file" required accept=".cetpro,.json"></label><label>Clave del archivo<input name="passphrase" type="password" minlength="8" required placeholder="Ej.: Aula2026!Computacion"></label><button type="submit">Actualizar acceso</button><p class="error" data-error></p></form></details><details><summary>Renovar vinculación mediante solicitud</summary><button id="renew-request">Descargar solicitud del equipo</button><form id="renew-form"><label>Vinculación renovada<input name="file" type="file" required accept=".cetpro,.json"></label><label>Huella confirmada con dirección<input name="fingerprint" required></label><button type="submit" class="primary">Aplicar renovación</button><p class="error" data-error></p></form></details>` : ''}</section></div>`;
  document.querySelector('#login-theme').onclick=()=>window.toggleCETPROTheme();
  bindForm('#recover-exchange-form',async(v,form)=>{await api('exchange/recover',{package:await readJSON(form.elements.file.files[0]),passphrase:v.passphrase});notice('Acceso actualizado. Ingresa con la contraseña indicada por dirección.');await authScreen();});
  const renew = document.querySelector('#renew-request'); if (renew) { renew.onclick = async () => download(await api('device-request'), 'SOLICITUD_RENOVACION.cetpro'); bindForm('#renew-form', async (v, form) => { await api('provision/accept', { package: await readJSON(form.elements.file.files[0]), fingerprint: v.fingerprint.trim() }); notice('Cuenta y autorización renovadas.'); await authScreen(); }); }
  document.querySelector('#show-password').onclick = event => { const field = document.querySelector('#password'); field.type = field.type === 'password' ? 'text' : 'password'; event.target.textContent = field.type === 'password' ? 'Mostrar' : 'Ocultar'; };
  bindForm('#login-form', async values => { const result = await api('login', values); token = result.token; sessionStorage.setItem('CETPRO_LOCAL_TOKEN', token); location.hash = '#/inicio'; await render(); });
}
function shell(route) {
  const teacher = data.user.role === 'DOCENTE', director = data.user.role === 'DIRECTOR';
  const links = [['inicio', '◈', 'Inicio'], ['estudiantes', '♙', teacher ? 'Mis estudiantes' : 'Estudiantes'], ...(!teacher ? [['matriculas', '▤', 'Matrículas']] : []), ['grupos', '▦', teacher ? 'Mis grupos' : 'Grupos'], ['evaluacion', '▥', teacher ? 'Notas' : 'Consultar notas'], ['asistencia', '✓', teacher ? 'Asistencia' : 'Consultar asistencia'], ['documentos', '▧', teacher ? 'Mis documentos' : 'Documentos'], ['configuracion-documental', '⚙', 'Datos de documentos'], ['entregas', '▤', 'Entregas y revisión'], ['datos','⇧','Actualizar y exportar datos'],['sincronizacion', '⇄', 'Sincronización'], ...(!teacher ? [['cuentas', '⚙', director ? 'Usuarios y asignaciones' : 'Registrar docentes']] : []), ...(director ? [['respaldo','□','Respaldo y migración']] : []), ['perfil', '○', 'Mi cuenta']];
  root.innerHTML = `<div class="shell"><aside class="sidebar"><div class="brand"><img src="/app/img/logo-cetpro.jpg" alt="CETPRO"><div><strong>CETPRO</strong><small>GESTIÓN ACADÉMICA</small></div></div><nav aria-label="Menú principal">${links.filter(([r])=>data.policy?.routes.includes(r)).map(([r, icon, title]) => `<a href="#/${r}" class="${route === r ? 'active' : ''}"><span aria-hidden="true">${icon}</span>${title}</a>`).join('')}</nav><div class="sidebar-bottom">● Sin internet<br>Equipo ${escape(data.status.deviceId.slice(0, 8))}<br>Última recepción: ${data.lastSync ? escape(new Date(data.lastSync.at).toLocaleString('es-PE')) : 'Sin intercambios'}</div></aside><div class="content"><header class="topbar"><span class="badge">${data.status.demonstration ? 'DEMO · Datos ficticios' : 'Guardado local'}</span><div class="identity"><div><strong>${escape(data.user.name)}</strong><small>${escape(roleName[data.user.role])}</small></div><button id="theme-toggle" class="small" aria-label="Cambiar modo claro u oscuro">${document.documentElement.dataset.theme==='dark'?'Modo claro':'Modo oscuro'}</button><button id="logout" class="small">Cerrar sesión</button></div></header><main class="page" id="page"></main></div></div>`;
  document.querySelector('#theme-toggle').onclick=event=>{const next=window.toggleCETPROTheme();event.target.textContent=next==='dark'?'Modo claro':'Modo oscuro';};
  document.querySelector('#logout').onclick = async () => { if (dirty && !confirm('Hay cambios sin guardar. ¿Cerrar sesión?')) return; try { await api('logout', {}); } finally { dirty = false; token = null; sessionStorage.removeItem('CETPRO_LOCAL_TOKEN'); await render(); } };
}
function home(page) {
  const teacher = data.user.role === 'DOCENTE';
  page.innerHTML = heading(`Hola, ${escape(data.user.name.split(' ')[0])}`, teacher ? 'Estas son tus aulas y tareas pendientes.' : 'Un vistazo al trabajo académico de la institución.') + `<div class="grid">${[['Estudiantes', data.students.length, 'Dentro de tu alcance'], ['Matrículas', data.enrollments.filter(e => e.active).length, 'Registros activos'], ['Grupos', data.groups.length, teacher ? 'Asignados a tu cuenta' : 'Grupos institucionales'], ['Cambios pendientes', data.pending, 'Confirmados al recibir respuesta institucional']].map(([title, n, desc]) => `<div class="card stat"><span class="muted">${title}</span><span class="number">${n}</span><p>${desc}</p></div>`).join('')}</div><h2>Continúa tu trabajo</h2><div class="grid">${(teacher ? [['asistencia', 'Tomar asistencia', 'Registra las marcas de tu sesión.'], ['evaluacion', 'Registrar notas', 'Completa las calificaciones por indicador.']] : [['matriculas', 'Nueva matrícula', 'Incorpora estudiantes al grupo correcto.'], ['grupos', 'Organización académica', 'Consulta periodos, módulos y grupos.']]).concat([['sincronizacion', 'Actualizar datos', 'Intercambia los cambios mediante USB.']]).map(([r, title, desc]) => `<a class="card link-card" href="#/${r}"><h2>${title} →</h2><p>${desc}</p></a>`).join('')}</div>${data.migrationReport?.conflicts.length ? `<div class="warning">La migración conserva ${data.migrationReport.conflicts.length} diferencias de origen para revisión. Consúltalas en Respaldo y migración.</div>` : ''}${data.conflicts.length ? `<div class="warning">Hay ${data.conflicts.length} conflictos por revisar en Sincronización. Se conservaron ambos valores.</div>` : ''}<div class="card"><h2>${teacher ? 'Tus aulas' : 'Grupos de la institución'}</h2>${data.groups.length ? data.groups.map(g => `<p><strong>${escape(groupLabel(g))}</strong><br><span class="muted">${escape(g.periodId || 'Periodo pendiente')} · ${escape(g.units.join(', ') || 'Unidades pendientes')} · ${g.closed ? 'Cerrado' : 'Abierto'}</span></p>`).join('') : '<p class="empty">Dirección debe asignarte tus grupos.</p>'}</div>`;
}
function students(page) {
  const canEdit = data.user.role !== 'DOCENTE';
  page.innerHTML = heading(canEdit ? 'Estudiantes' : 'Mis estudiantes', 'Busca por nombre o documento. Cada matrícula conserva su historial.') + `${canEdit ? `<div class="card"><h2>Registrar o actualizar estudiante</h2><form id="student-form"><input type="hidden" name="id"><input type="hidden" name="rev"><div class="form-grid"><label>Nombre completo<input name="name" required placeholder="Ej.: Pérez Gómez, Ana María"></label><label>Documento de identidad<input name="document" required placeholder="Ej.: 00112233 (conservar ceros)"></label><label>Apellido paterno<input name="lastName1" placeholder="Ej.: Pérez"></label><label>Apellido materno<input name="lastName2" placeholder="Ej.: Gómez"></label><label>Nombres<input name="firstNames" placeholder="Ej.: Ana María"></label><label>Sexo según plantilla<select name="sex"><option value="">Pendiente</option><option value="H">H - Hombre</option><option value="M">M - Mujer</option></select></label><label>Fecha de nacimiento<input name="birthDate" type="date"></label><label>Tipo de documento<input name="documentType" placeholder="DNI, CE…"></label></div><label><input type="checkbox" name="active" checked>Estudiante activo</label><div class="actions"><button type="submit" class="primary">Guardar estudiante</button><button type="button" id="student-reset">Nuevo registro</button></div><p class="error" data-error></p></form></div>` : ''}<div class="card"><label>Buscar estudiante<input id="student-search" placeholder="Nombre o documento…" type="search"></label><div class="table-wrap"><table><thead><tr><th>Estudiante</th><th>Documento</th><th>Estado</th>${canEdit ? '<th>Acción</th>' : ''}</tr></thead><tbody id="student-rows"></tbody></table></div></div>`;
  const draw = query => { document.querySelector('#student-rows').innerHTML = data.students.filter(s=>!s.archived).filter(s => `${s.name} ${s.document}`.toLowerCase().includes(query.toLowerCase())).map(s => `<tr><td>${escape(s.name)}</td><td>${escape(s.document)}</td><td>${s.active ? 'Activo' : 'Inactivo'}</td>${canEdit ? `<td><button class="small" data-edit="${escape(s.id)}">Editar</button> <button class="small" data-delete-student="${escape(s.id)}">Eliminar</button></td>` : ''}</tr>`).join('') || '<tr><td colspan="4" class="empty">Sin resultados.</td></tr>'; };
  if(canEdit&&data.students.some(s=>s.archived)){const archived=document.createElement('details');archived.className='card';archived.innerHTML='<summary>Estudiantes eliminados: historial conservado</summary>'+data.students.filter(s=>s.archived).map(s=>`<p>${escape(s.name)} · ${escape(s.document)} <button data-restore-student="${escape(s.id)}">Restaurar ficha</button></p>`).join('');page.append(archived);archived.querySelectorAll('[data-restore-student]').forEach(button=>button.onclick=async()=>{const student=data.students.find(s=>s.id===button.dataset.restoreStudent);try{await api('students',{...student,rev:student.rev,active:true,archived:false});notice('Ficha restaurada. Registra una matrícula nueva cuando corresponda.');await render();}catch(err){notice(err.message,true);}});}
  draw(''); document.querySelector('#student-search').oninput = e => draw(e.target.value);
  if (canEdit) {
    document.querySelector('#student-rows').onclick = async e => { if(e.target.dataset.deleteStudent){const student=data.students.find(s=>s.id===e.target.dataset.deleteStudent),reason=prompt('Motivo de eliminación (se conserva el historial de notas y asistencia):');if(!reason)return;try{await api('students/archive',{id:student.id,rev:student.rev,reason,date:today()});notice('Estudiante eliminado del padrón activo; historial conservado.');await render();}catch(err){notice(err.message,true);}return;}const s = data.students.find(s => s.id === e.target.dataset.edit); if (!s) return; const f = document.querySelector('#student-form'); for (const key of ['id', 'rev', 'name', 'document']) f.elements[key].value = s[key]; f.elements.active.checked = s.active; for(const key of ['lastName1','lastName2','firstNames','sex','birthDate','documentType'])f.elements[key].value=s[key]??s.legacy?.[{lastName1:'apellidoPaterno',lastName2:'apellidoMaterno',firstNames:'nombres',sex:'sexo',birthDate:'fechaNacimiento',documentType:'tipoDocumento'}[key]]??''; f.scrollIntoView({ behavior: 'auto' }); };
    document.querySelector('#student-reset').onclick = () => {const form=document.querySelector('#student-form');form.reset();form.elements.id.value='';form.elements.rev.value='';};
    bindForm('#student-form', async v => { await api('students', { ...v, id: v.id || undefined, rev: v.rev || null, active: v.active === 'on' }); notice('Estudiante guardado en este equipo.'); await render(); });
  }
}
function enrollments(page) {
  page.innerHTML = heading('Matrículas', 'Los estudiantes nuevos se incorporan sin modificar notas ni asistencias existentes.') + `<div class="card"><h2>Nueva matrícula</h2><form id="enrollment-form"><div class="form-grid"><label>Estudiante<select name="studentId" required><option value="">Seleccionar…</option>${options(data.students.filter(s => s.active))}</select></label><label>Grupo<select name="groupId" required><option value="">Seleccionar…</option>${options(data.groups.filter(g => g.periodId && g.moduleId), null, groupLabel)}</select></label><label>Fecha de ingreso<input name="startDate" type="date" value="${today()}" required></label></div><p class="muted">Si un grupo no aparece, dirección debe configurar su periodo y módulo.</p><p class="error" data-error></p><button type="submit" class="primary">Registrar matrícula</button></form></div><div class="card"><h2>Matrículas registradas</h2><div class="table-wrap"><table><thead><tr><th>Estudiante</th><th>Grupo</th><th>Periodo</th><th>Código de matrícula</th><th>Ingreso</th><th>Estado / Acción</th></tr></thead><tbody>${data.enrollments.map(e => `<tr><td>${escape(studentName(e))}</td><td>${escape(data.groups.find(g=>g.id===e.groupId)?.name||e.groupId)}</td><td>${escape(e.periodId || 'Pendiente')}</td><td>${escape(e.code||'Pendiente de actualización')}</td><td>${escape(e.startDate || 'Fecha de origen pendiente')}</td><td>${e.active ? `<button class="small" data-retire="${escape(e.id)}">Retiro / traslado</button>` : 'Retirado'}</td></tr>`).join('')}</tbody></table></div></div>`;
  page.querySelectorAll('[data-retire]').forEach(button => button.onclick = async () => { const enrollment = data.enrollments.find(e => e.id === button.dataset.retire); const reason = prompt('Motivo del retiro o traslado:'); if (!reason) return; const targetGroupId = prompt('Para traslado, escribe el código de grupo destino. Para retiro, déjalo vacío. Grupos disponibles: ' + data.groups.map(g => g.id).join(', ')) || ''; try { await api('enrollments/retire', { id: enrollment.id, rev: enrollment.rev, reason, date: today(), targetGroupId }); notice('Matrícula actualizada; notas y asistencias anteriores conservadas.'); await render(); } catch (e) { notice(e.message, true); } });
  bindForm('#enrollment-form', async v => { await api('enrollments', v); notice('Matrícula guardada. Envíe la actualización al docente.'); await render(); });
}
function groups(page) {
  const director = data.user.role === 'DIRECTOR';
  page.innerHTML = heading(director ? 'Organización de grupos' : data.user.role === 'DOCENTE' ? 'Mis grupos' : 'Grupos académicos', 'Periodo, módulo y unidades determinan el alcance de los registros.') + (director ? `<div class="card"><h2>Nuevo grupo</h2><form id="new-group-form"><div class="form-grid"><label>Nombre descriptivo del grupo<input name="name" required placeholder="Ej.: Informática, grupo A, mañana"></label><label>Carrera<select name="programId" id="new-group-program">${options(data.programs,null,p=>p.nombre)}</select></label><label>Módulo<select name="moduleId" id="new-group-module"></select></label><label>Periodo<input name="periodId" required placeholder="Ej.: 2026-II"></label><label>Sección<input name="section" placeholder="Ej.: A, B o ÚNICA" maxlength="20" required></label><label>Turno<input name="turno" placeholder="Ej.: Mañana, tarde o noche" maxlength="60"></label><label>Unidades separadas por coma<input name="units" required placeholder="UD1, UD2, EFSRT"></label></div><button type="submit" class="primary">Crear grupo</button><p class="error" data-error></p></form></div>` : '') + `<div class="card toolbar"><label>Filtrar carrera<select id="groups-program-filter"><option value="">Todas las carreras permitidas</option>${options(data.programs,null,p=>p.nombre)}</select></label><label>Buscar grupo<input id="groups-search" placeholder="Ej.: Informática, mañana o 2026-II"></label></div>` + data.groups.map(g => `<div class="card" data-group-card="${escape(g.id)}"><h2>${escape(groupLabel(g))}</h2><p><span class="badge">${g.closed ? 'Cerrado' : 'Abierto'}</span> ${escape(g.periodId || 'Periodo pendiente')}</p>${director ? `<form class="group-form" data-id="${escape(g.id)}"><div class="form-grid"><label>Nombre del grupo<input name="name" value="${escape(g.rawName||g.name)}" placeholder="Ej.: Informática, grupo A, mañana" required></label><label>Sección<input name="section" value="${escape(g.section||'')}" placeholder="Ej.: A, B o ÚNICA" maxlength="20"></label><label>Turno<input name="turno" value="${escape(g.turno||'')}" placeholder="Ej.: Mañana" maxlength="60"></label><label>Periodo académico<input name="periodId" value="${escape(g.periodId)}" placeholder="Ej. 2026-I" required></label><label>Módulo<select name="moduleId"><option value="">Seleccionar…</option>${options(data.modules.filter(m => m.programaId === g.programId), g.moduleId, m => m.nombre || m.id)}</select></label><label>Unidades separadas por coma<input name="units" value="${escape(g.units.join(', '))}" placeholder="UD1, UD2…" required></label></div><div class="actions"><button type="submit" class="primary">Guardar configuración</button><button type="button" class="small" data-close="${escape(g.id)}">${g.closed ? 'Autorizar reapertura' : 'Cerrar registro'}</button></div><p class="error" data-error></p></form>` : `<p>Unidades: ${escape(g.units.join(', ') || 'Pendientes')}</p>`}</div>`).join('');
  if (director) { const updateModules = () => document.querySelector('#new-group-module').innerHTML = options(data.modules.filter(m => m.programaId === document.querySelector('#new-group-program').value), null, m => m.nombre); document.querySelector('#new-group-program').onchange = updateModules; updateModules(); bindForm('#new-group-form', async v => { await api('groups', { ...v, units: v.units.split(',') }); notice('Nuevo grupo creado.'); await render(); }); }
  const filterGroups=()=>{const program=page.querySelector('#groups-program-filter').value,query=page.querySelector('#groups-search').value.toLowerCase();page.querySelectorAll('[data-group-card]').forEach(card=>{const g=data.groups.find(g=>g.id===card.dataset.groupCard);card.hidden=!!(program&&g.programId!==program)||!groupLabel(g).toLowerCase().includes(query);});};page.querySelector('#groups-program-filter').onchange=filterGroups;page.querySelector('#groups-search').oninput=filterGroups;
  document.querySelectorAll('.group-form').forEach((form, i) => { form.id = `group-form-${i}`; bindForm(`#${form.id}`, async v => { const g = data.groups.find(g => g.id === form.dataset.id); await api('groups', { ...v, id: g.id, rev: g.rev, units: v.units.split(',') }); notice('Configuración académica guardada.'); await render(); }); });
  page.onclick = async e => { const g = data.groups.find(g => g.id === e.target.dataset.close); if (!g) return; const reason = prompt('Motivo del cierre o reapertura:'); if (!reason) return; try { await api('closure', { groupId: g.id, closed: !g.closed, rev: g.rev, reason }); notice('Estado actualizado y auditado.'); await render(); } catch (e) { notice(e.message, true); } };
}
function academic(page, entity) {
  const teacher = data.user.role === 'DOCENTE', attendance = entity === 'attendance';
  const stored = sessionStorage.getItem(`CETPRO_${entity}_GROUP`), group = data.groups.find(g => g.id === stored) || data.groups[0];
  if (!group) { page.innerHTML = heading(attendance ? 'Asistencia' : 'Notas', 'No hay grupos asignados.') + '<div class="card empty">Dirección debe asignar un grupo y sus unidades a tu cuenta.</div>'; return; }
  const units = teacher ? group.units.filter(u => data.user.assignments.some(a => a.groupId === group.id && a.units.includes(u))) : group.units;
  page.innerHTML = heading(attendance ? 'Control de asistencia' : 'Registro de notas', teacher ? 'Los cambios se guardan en este equipo y se envían al sincronizar.' : 'Consulta de registros consolidados. Las correcciones corresponden al docente.') + `<div class="card"><div class="toolbar"><label>Grupo<select id="academic-group">${options(data.groups, group.id, groupLabel)}</select></label><label>Unidad<select id="academic-unit">${units.map(u => `<option>${escape(u)}</option>`).join('')}</select></label>${attendance ? `<label>Fecha<input id="academic-date" type="date" value="${today()}"></label><label>Sesión<input id="academic-session" value="1" placeholder="Ej. 1"></label>` : '<label>Indicador<input id="academic-indicator" value="IL1" placeholder="Ej. IL1"></label>'}</div>${group.closed ? '<div class="warning">Registro cerrado. Dirección puede autorizar una reapertura con motivo.</div>' : ''}${!group.periodId || !group.moduleId || !units.length ? '<div class="warning">Dirección debe completar el periodo, módulo y unidades de este grupo.</div>' : ''}${attendance ? '<div class="actions"><button id="attendance-document">Ver y exportar ficha de asistencia</button></div>' : ''}${attendance && teacher ? '<div class="actions"><button id="all-present" class="small">Marcar presentes en esta sesión</button></div>' : ''}<p class="muted">${attendance ? 'P: presente · F: falta · J: justificada · T: tardanza. Las marcas previas al ingreso permanecen sin registrar.' : 'Escala de registro: 0–20. Una celda vacía significa pendiente; cero es una calificación.'}</p><div class="table-wrap"><table><thead><tr><th>Estudiante</th><th>${attendance ? 'Estado' : 'Nota'}</th><th>Observación</th></tr></thead><tbody id="academic-rows"></tbody></table></div><div class="actions">${teacher ? '<button id="save-academic" class="primary">Guardar cambios</button>' : ''}<span id="save-state" class="save-state" role="status">Sin cambios pendientes</span></div></div>${attendance ? '<div class="card"><h2>Resumen mensual</h2><label>Mes<input type="month" id="attendance-month" value="' + today().slice(0, 7) + '"></label><div id="monthly-summary"></div></div>' : ''}`;
  let base = new Map();
  const context = () => ({ groupId: group.id, unit: document.querySelector('#academic-unit').value, ...(attendance ? { date: document.querySelector('#academic-date').value, session: document.querySelector('#academic-session').value } : { indicator: document.querySelector('#academic-indicator').value }) });
  const roster = () => data.enrollments.filter(e => e.groupId === group.id && e.active).sort((a,b) => studentName(a).localeCompare(studentName(b), 'es'));
  if(attendance)document.querySelector('#attendance-document').onclick=()=>{if(dirty){notice('Guarda la asistencia antes de generar su ficha.',true);return;}sessionStorage.setItem('CETPRO_DOCUMENT_SELECTION',JSON.stringify({groupId:document.querySelector('#academic-group').value,unit:document.querySelector('#academic-unit').value}));location.hash='#/documentos';};
  const draw = () => {
    base = new Map(); const c = context();
    document.querySelector('#academic-rows').innerHTML = roster().map(e => {
      const r = data[entity].find(r => r.enrollmentId === e.id && r.unit === c.unit && (attendance ? r.date === c.date && r.session === c.session : r.indicator === c.indicator)); base.set(e.id, r || null);
      const disabled = !teacher || group.closed || !c.unit || (attendance && e.startDate && c.date < e.startDate);
      return `<tr data-enrollment="${escape(e.id)}"><td class="student">${escape(studentName(e))}<small>${escape(data.students.find(s => s.id === e.studentId)?.document)}</small></td><td>${attendance ? `<select class="academic-value"${disabled ? ' disabled' : ''}><option value="">Sin registrar</option>${['P', 'F', 'J', 'T'].map(v => `<option${r?.value === v ? ' selected' : ''}>${v}</option>`).join('')}</select>` : `<input class="academic-value note" type="number" min="0" max="20" step="0.01" value="${escape(r?.value)}" aria-label="Nota de ${escape(studentName(e))}"${disabled ? ' disabled' : ''}>`}</td><td><input class="academic-observation" value="${escape(r?.observation)}" aria-label="Observación de ${escape(studentName(e))}"${disabled ? ' disabled' : ''}></td></tr>`;
    }).join('') || '<tr><td colspan="3" class="empty">No hay estudiantes matriculados.</td></tr>'; dirty = false;
    if (attendance) monthly();
  };
  function markDirty() { dirty = true; document.querySelector('#save-state').textContent = 'Cambios sin guardar'; document.querySelector('#save-state').className = 'save-state unsaved'; }
  function monthly() { const month = document.querySelector('#attendance-month').value, unit = context().unit; document.querySelector('#monthly-summary').innerHTML = `<div class="table-wrap"><table><thead><tr><th>Estudiante</th><th>P</th><th>F</th><th>J</th><th>T</th></tr></thead><tbody>${roster().map(e => { const marks = data.attendance.filter(r => r.enrollmentId === e.id && r.unit === unit && r.date.startsWith(month)); return `<tr><td>${escape(studentName(e))}</td>${['P', 'F', 'J', 'T'].map(state => `<td>${marks.filter(r => r.value === state).length}</td>`).join('')}</tr>`; }).join('')}</tbody></table></div>`; }
  draw();
  document.querySelector('#academic-rows').oninput = markDirty;
  document.querySelector('#academic-rows').onkeydown = event => { if (event.key === 'Enter') { event.preventDefault(); const inputs = [...document.querySelectorAll('.academic-value:not(:disabled)')], index = inputs.indexOf(event.target); inputs[index + 1]?.focus(); } };
  document.querySelector('#academic-group').onchange = async e => { if (dirty && !confirm('Hay cambios sin guardar. ¿Cambiar de grupo?')) { e.target.value = group.id; return; } dirty = false; sessionStorage.setItem(`CETPRO_${entity}_GROUP`, e.target.value); await render(); };
  for (const selector of ['#academic-unit', ...(attendance ? ['#academic-date', '#academic-session'] : ['#academic-indicator'])]) { const field = document.querySelector(selector); field.dataset.previous = field.value; field.onchange = () => { if (dirty && !confirm('Hay cambios sin guardar. ¿Cambiar el contexto?')) { field.value = field.dataset.previous; return; } field.dataset.previous = field.value; draw(); document.querySelector('#save-state').textContent = 'Sin cambios pendientes'; }; }
  if (attendance) { document.querySelector('#attendance-month').onchange = monthly; const all = document.querySelector('#all-present'); if (all) all.onclick = () => { if (!confirm('Se marcará presente a cada estudiante habilitado. Revisa las marcas antes de guardar.')) return; document.querySelectorAll('.academic-value:not(:disabled)').forEach(field => field.value = 'P'); markDirty(); }; }
  const save = document.querySelector('#save-academic'); if (save) save.onclick = async () => {
    const rows = [...document.querySelectorAll('#academic-rows tr[data-enrollment]')].map(row => { const field = row.querySelector('.academic-value'), observation = row.querySelector('.academic-observation').value, old = base.get(row.dataset.enrollment); const value = attendance ? field.value || null : field.value === '' ? null : Number(field.value); return { enrollmentId: row.dataset.enrollment, value, observation, rev: old?.rev || null, clear: value === null && old?.value != null, changed: !field.disabled && (field.value !== '' || old?.value != null) && (value !== old?.value || observation !== (old?.observation || '')) }; }).filter(row => row.changed);
    if (rows.some(r => r.clear) && !confirm('Un registro existente quedará pendiente. Se conservará el historial. ¿Continuar?')) return;
    if (!rows.length) { notice('No hay cambios para guardar.'); return; }
    save.disabled = true;
    try { const result = await api(entity, { ...context(), rows }); for (const r of result) { const index = data[entity].findIndex(v => v.id === r.id); index < 0 ? data[entity].push(r) : data[entity][index] = r; } dirty = false; draw(); document.querySelector('#save-state').textContent = `Guardado en este equipo · ${result.length} registros. Pendiente de enviar.`; document.querySelector('#save-state').className = 'save-state'; notice('Cambios guardados.'); } catch (e) { document.querySelector('#save-state').textContent = `No se guardó: ${e.message}`; notice(e.message, true); } finally { save.disabled = false; }
  };
}
async function accounts(page) {
  const users = await api('users');
  page.innerHTML = heading('Cuentas y asignaciones', 'Cada persona accede únicamente a las funciones y aulas de su cuenta.') + `<div class="card"><h2>Crear o actualizar cuenta</h2><form id="account-form"><input type="hidden" name="id"><input type="hidden" name="version"><div class="form-grid"><label>Nombre completo<input name="name" required placeholder="Ej.: Ana María Pérez Gómez"></label><label>Usuario<input name="username" required pattern="[a-zA-Z0-9._-]{3,60}" placeholder="Ej.: docente.informatica.manana"></label><label>Profesor, carrera y grupo<textarea name="description" placeholder="Ej.: Ana Pérez, docente de Informática, grupo A, turno mañana"></textarea></label><label>Rol<select name="role">${(data.policy?.users||[]).map(role=>`<option value="${role}">${roleName[role]}</option>`).join('')}</select></label><label>Contraseña inicial o recuperación<input name="password" type="password" minlength="8" autocomplete="new-password" placeholder="Nueva: mínimo 8 caracteres; vacía conserva la actual"></label></div><label><input type="checkbox" name="active" checked>Cuenta activa</label><h2>Asignaciones docentes</h2><label>Carrera / programa<select id="account-program-filter"><option value="">Todas las carreras</option>${options(data.programs,null,p=>p.nombre)}</select></label><p class="muted">Selecciona las unidades permitidas. Los grupos sin configurar no admiten asignación.</p><div id="assignments">${data.groups.filter(g => g.units.length).map(g => `<div class="assignment" data-group="${escape(g.id)}"><strong>${escape(groupLabel(g))}</strong><p class="muted">Periodo ${escape(g.periodId)}</p><div class="checks">${g.units.map(u => `<label><input type="checkbox" value="${escape(u)}">${escape(u)}</label>`).join('')}</div></div>`).join('') || '<p>Configura primero las unidades en Grupos.</p>'}</div><p class="error" data-error></p><div class="actions"><button type="submit" class="primary">Guardar cuenta</button><button type="button" id="new-account">Nueva cuenta</button></div></form></div><div class="card"><h2>Usuarios de la institución</h2><div class="table-wrap"><table><thead><tr><th>Persona</th><th>Usuario</th><th>Rol</th><th>Grupos</th><th>Acción</th></tr></thead><tbody>${users.filter(u=>!u.archived).map(u => `<tr><td>${escape(u.name)}<small>${escape(u.description||'')}</small><small>${u.active ? 'Activo' : 'Desactivado'}</small></td><td>${escape(u.username)}</td><td>${escape(roleName[u.role])}</td><td>${escape(u.assignments.map(a => data.groups.find(g=>g.id===a.groupId)?.name||a.groupId).join(', '))}</td><td>${`<button data-user="${escape(u.id)}" class="small">Editar</button><button data-delete-user="${escape(u.id)}" class="small"${u.id===data.user.id?' disabled':''}>Eliminar</button>`}</td></tr>`).join('')}</tbody></table></div></div>`;
  if(users.some(u=>u.archived)){const archived=document.createElement('details');archived.className='card';archived.innerHTML='<summary>Usuarios eliminados</summary>'+users.filter(u=>u.archived).map(u=>`<p>${escape(u.name)} · ${escape(u.username)} <button data-restore-user="${escape(u.id)}">Restaurar usuario</button></p>`).join('');page.append(archived);archived.querySelectorAll('[data-restore-user]').forEach(button=>button.onclick=async()=>{const u=users.find(u=>u.id===button.dataset.restoreUser);try{await api('users',{...u,active:true,archived:false});notice(data.status.authority?'Usuario restaurado.':'Restauración preparada; envía las solicitudes a dirección.');await render();}catch(err){notice(err.message,true);}});}
  const form = document.querySelector('#account-form');document.querySelector('#account-program-filter').onchange=event=>{document.querySelectorAll('#assignments [data-group]').forEach(row=>row.hidden=!!event.target.value&&data.groups.find(g=>g.id===row.dataset.group)?.programId!==event.target.value);};
  if(data.accountRequests?.length){const requestBox=document.createElement('div');requestBox.className='card';requestBox.innerHTML='<h2>Altas docentes preparadas sin conexión</h2>'+data.accountRequests.map(r=>`<div class="request-card"><strong>${escape(r.name)}</strong><p>${escape(r.description)} · ${escape(r.username)} · ${escape(r.status)}</p>${r.status==='REQUESTED'&&data.status.authority?`<button class="small" data-account-request="${r.id}">${r.action==='PASSWORD'?'Confirmar contraseña':r.action==='UPDATE'?'Aplicar actualización':'Activar cuenta docente'}</button><button data-reject-account="${escape(r.id)}" class="small">Rechazar solicitud</button>`:''}</div>`).join('');page.append(requestBox);requestBox.querySelectorAll('[data-reject-account]').forEach(button=>button.onclick=async()=>{const reason=prompt('Motivo del rechazo:');if(!reason)return;try{await api('users/reject-request',{id:button.dataset.rejectAccount,reason});await render();}catch(err){notice(err.message,true);}});requestBox.querySelectorAll('[data-account-request]').forEach(button=>button.onclick=async()=>{try{await api('users/accept-request',{id:button.dataset.accountRequest});notice('Cuenta docente creada. Vincula su computadora para que pueda entrar.');await render();}catch(error){notice(error.message,true);}});}
  document.querySelectorAll('[data-user]').forEach(button => button.onclick = () => { const u = users.find(u => u.id === button.dataset.user); for (const key of ['id','version', 'name', 'username', 'role','description']) form.elements[key].value = u[key]||''; form.elements.password.value = ''; form.elements.active.checked = u.active; document.querySelectorAll('#assignments input').forEach(field => field.checked = u.assignments.some(a => a.groupId === field.closest('[data-group]').dataset.group && a.units.includes(field.value))); form.scrollIntoView({ behavior: 'auto' }); });
  document.querySelectorAll('[data-delete-user]').forEach(button=>button.onclick=async()=>{const u=users.find(u=>u.id===button.dataset.deleteUser),reason=prompt('Motivo de eliminación del usuario (su trabajo se conserva):');if(!reason)return;try{await api('users/archive',{id:u.id,version:u.version,reason});notice(data.status.authority?'Usuario eliminado; trabajo conservado.':'Solicitud de eliminación preparada. Exporta la actualización a dirección.');await render();}catch(err){notice(err.message,true);}});
  document.querySelector('#new-account').onclick = () => { form.reset(); form.elements.id.value = '';form.elements.version.value=''; };
  configureTeacherAssignments(page,{data,escape});
  bindForm('#account-form', async v => { const assignments = [...document.querySelectorAll('#assignments [data-group]')].map(row => ({ groupId: row.dataset.group,section:row.dataset.section||undefined, units: [...row.querySelectorAll('input:checked')].map(f => f.value) })).filter(a => a.units.length); const result=await api('users', { ...v, id: v.id || undefined,version:v.version?Number(v.version):undefined, active: v.active === 'on', assignments }); notice(result.status==='REQUESTED'?'Cambio docente preparado. Exporta con Incluir solicitudes de usuarios y llévalo al equipo institucional.':'Cuenta guardada. Actualiza los equipos vinculados si cambió su asignación.'); await render(); });
}
async function sync(page) {
  const hub = data.status.authority, director = data.user.role === 'DIRECTOR', users = director ? await api('users') : [];
  page.innerHTML = heading('Sincronización entre equipos', 'Envía tu trabajo o recibe una actualización siguiendo los pasos. Funciona sin internet mediante USB.') + `<div class="section-note"><p>Guardado local y recepción institucional son estados diferentes. Los cambios pendientes se confirman cuando regresa una actualización del equipo institucional.</p></div><div class="grid"><div class="card"><h2>1. Enviar cambios</h2><p>${hub ? 'Selecciona el equipo que recibirá los datos de su cuenta.' : 'Entrega este archivo a secretaría o dirección para consolidar tu trabajo.'}</p>${hub ? `<label>Equipo destinatario<select id="sync-device"><option value="">Seleccionar…</option>${options(data.devices.filter(d => d.id !== data.status.deviceId), null, d => `${users.find(u => u.id === d.userId)?.name || d.name || d.userId} · ${d.id.slice(0, 8)}`)}</select></label>` : ''}<button class="primary" id="sync-export">Descargar cambios</button><p class="muted">${data.pending} operaciones pendientes de confirmación.</p></div><div class="card"><h2>2. Recibir cambios</h2><label class="file">Paquete recibido<input id="sync-file" type="file" accept=".cetpro,.json"></label><div id="sync-preview" class="summary"></div><div class="actions"><button id="sync-apply" class="primary" disabled>Aplicar actualización revisada</button></div></div></div>${director && hub ? `<div class="card"><h2>Vincular un nuevo equipo</h2><p>El equipo nuevo descarga su solicitud desde la pantalla inicial. Selecciona aquí la cuenta que usará.</p><form id="provision-form"><div class="form-grid"><label>Solicitud del equipo<input name="file" type="file" required accept=".cetpro,.json"></label><label>Cuenta asignada<select name="userId">${options(users.filter(u => u.active && u.role !== 'DIRECTOR'))}</select></label></div><button type="submit" class="primary">Generar vinculación cifrada</button><p class="error" data-error></p></form><p>Huella institucional que debes confirmar con el destinatario:</p><p class="mono">${escape(data.status.fingerprint)}</p></div>` : ''}${director ? `<div class="card"><h2>Conflictos conservados</h2>${data.conflicts.map(c => `<div class="assignment"><strong>${escape(c.kind === 'pending' ? 'Dependencia pendiente' : 'Edición incompatible')} · ${escape(c.operation.body.entity)}</strong><p>Registro ${escape(c.operation.body.recordId)}</p><p>Valor actual: <span class="mono">${escape(JSON.stringify(c.current))}</span></p><p>Propuesta recibida: <span class="mono">${escape(JSON.stringify(c.operation.body.value))}</span></p><div class="actions"><button data-conflict="${escape(c.id)}" data-action="KEEP_LOCAL">Conservar actual</button><button data-conflict="${escape(c.id)}" data-action="ACCEPT_INCOMING">Aceptar recibido con motivo</button></div></div>`).join('') || '<p class="muted">No hay conflictos por resolver.</p>'}</div>` : ''}`;
  document.querySelector('#sync-export').onclick = async () => { try { download(await api('sync/export', { deviceId: document.querySelector('#sync-device')?.value }), `CAMBIOS_CETPRO_${today()}.cetpro`); notice('Archivo exportado. Entrega el USB al equipo destinatario.'); } catch (e) { notice(e.message, true); } };
  await renderPortableExchange(page,{data,api,escape,options,notice,render});
  currentPackage = null;
  document.querySelector('#sync-file').onchange = async event => { const button = document.querySelector('#sync-apply'), preview = document.querySelector('#sync-preview'); button.disabled = true; currentPackage = null; try { const pkg = await readJSON(event.target.files[0]), report = await api('sync/preview', { package: pkg }); preview.innerHTML = `<p><strong>Resultado de revisión</strong></p><p>${report.newRecords} altas · ${report.updates} actualizaciones · ${report.duplicates} ya recibidas</p><p>${report.conflicts} conflictos · ${report.pending} pendientes</p>${report.duplicatePackage ? '<p>Este paquete ya fue recibido.</p>' : ''}`; if (!report.duplicatePackage) { currentPackage = pkg; button.disabled = false; } } catch (e) { preview.textContent = e.message; notice(e.message, true); } };
  document.querySelector('#sync-apply').onclick = async event => { if (!currentPackage) return; event.target.disabled = true; try { const result = await api('sync/import', { package: currentPackage }); notice(`Actualización aplicada: ${result.newRecords} altas, ${result.updates} cambios, ${result.conflicts} conflictos conservados.`); currentPackage = null; await render(); } catch (e) { notice(e.message, true); event.target.disabled = false; } };
  bindForm('#provision-form', async (v, form) => { download(await api('provision', { userId: v.userId, request: await readJSON(form.elements.file.files[0]) }), 'VINCULACION_EQUIPO.cetpro'); notice('Vinculación exportada. Confirma la huella con el destinatario.'); });
  document.querySelectorAll('[data-conflict]').forEach(button => button.onclick = async () => { const reason = prompt('Motivo de la decisión (conservaremos el historial):'); if (!reason) return; try { await api('conflicts/resolve', { id: button.dataset.conflict, currentRev: data.conflicts.find(c => c.id === button.dataset.conflict)?.current?.rev || null, action: button.dataset.action, reason }); notice('Decisión registrada.'); await render(); } catch (e) { notice(e.message, true); } });
}
async function legacyFromBrowser() {
  const payload = { stores: {}, etapa2: {}, source: 'BROWSER_LEGACY' };
  const databases = await indexedDB.databases();
  const name = databases.some(d => d.name === 'CETPRO_V2_CANDIDATE') ? 'CETPRO_V2_CANDIDATE' : databases.some(d => d.name === 'CETPRO_DB') ? 'CETPRO_DB' : null;
  if (!name) throw new Error('No hay una base anterior en este navegador/origen. Importa su respaldo JSON.');
  const db = await new Promise((resolve, reject) => { const request = indexedDB.open(name); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); });
  try { for (const entity of db.objectStoreNames) payload.stores[entity] = await new Promise((resolve, reject) => { const request = db.transaction(entity).objectStore(entity).getAll(); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); } finally { db.close(); }
  for (let i = 0; i < localStorage.length; i++) { const key = localStorage.key(i); if (key.startsWith('CETPRO_ETAPA2_')) payload.etapa2[key] = JSON.parse(localStorage.getItem(key)); }
  return payload;
}
async function backup(page) {
  page.innerHTML = heading('Respaldo y migración', 'Conserva una copia recuperable antes de migrar o sincronizar.') + `<div class="card"><h2>Estado de la base de datos</h2><button id="database-check">Comprobar integridad y relaciones</button><div id="database-health" role="status"><p>Comprobando la base…</p></div></div><div class="card"><h2>Copia de seguridad completa</h2><p>La copia incluye datos, historial, cuentas y claves del equipo. Se guarda en la carpeta privada del servicio y debe custodiarse como la base original.</p><button id="backup" class="primary">Crear copia completa</button><p id="backup-status" class="mono"></p></div><div class="card"><h2>Incorporar datos del sistema anterior</h2><p>Los registros existentes se conservan. Las diferencias se presentan para revisión y la fuente original queda archivada.</p><div class="actions"><button id="read-legacy">Leer datos del navegador anterior</button><label>O seleccionar respaldo JSON<input type="file" id="legacy-file" accept=".json"></label></div><div id="legacy-preview"></div><button id="import-legacy" class="primary" disabled>Confirmar incorporación</button><div id="legacy-result"></div></div>${data.migrationReport ? `<div class="card"><h2>Diferencias de la última migración</h2><pre class="mono">${escape(JSON.stringify(data.migrationReport.conflicts, null, 2))}</pre></div>` : ''}<div class="card"><h2>Recuperación</h2><p>Detén el servicio y ejecuta <span class="mono">node scripts/restore-offline.cjs RUTA_DEL_RESPALDO</span>. El proceso verifica la integridad y crea otra copia antes de recuperar.</p></div>`;
  const checkHealth=async()=>{try{const r=await api('database/health');if(!page.isConnected)return;document.querySelector('#database-health').innerHTML=`<p><strong>${r.healthy?'Base físicamente correcta y sin relaciones rotas.':'Hay incidencias que necesitan revisión.'}</strong></p><p>${r.counts.students} estudiantes · ${r.counts.enrollments} matrículas · ${r.counts.groups} aulas.</p><p>${r.errors.length} errores de relación · ${r.warnings.length} datos pendientes o históricos por revisar.</p><details><summary>Ver resultados de revisión</summary>${[...r.errors,...r.warnings].map(i=>`<p>${escape(i.message)} <small>${escape(i.id)}</small></p>`).join('')||'<p>No hay incidencias.</p>'}</details><p>Se crea una copia privada diaria cuando se inicia el servicio. Las copias no se eliminan automáticamente. Conserva periódicamente otra copia en una unidad externa; una copia en el mismo disco no protege ante una avería de ese disco.</p>`;}catch(err){notice(err.message,true);}};document.querySelector('#database-check').onclick=checkHealth;await checkHealth();
  document.querySelector('#backup').onclick = async () => { try { const result = await api('backup', {}); document.querySelector('#backup-status').textContent = `private-data/backups/${result.filename}`; notice('Copia completa creada.'); } catch (e) { notice(e.message, true); } };
  let pkg;
  function preview(value) { pkg = value; document.querySelector('#legacy-preview').innerHTML = `<p>${value.stores?.estudiantes?.length || 0} estudiantes · ${value.stores?.matriculas?.length || 0} matrículas · ${value.stores?.evaluacion?.length || 0} evaluaciones · ${value.stores?.asistencia?.length || 0} asistencias · ${Object.keys(value.etapa2 || {}).length} registros de etapa 2.</p>`; document.querySelector('#import-legacy').disabled = false; }
  document.querySelector('#read-legacy').onclick = async () => { try { preview(await legacyFromBrowser()); } catch (e) { notice(e.message, true); } };
  document.querySelector('#legacy-file').onchange = async e => { try { preview(await readJSON(e.target.files[0])); } catch (e) { notice(e.message, true); } };
  document.querySelector('#import-legacy').onclick = async e => { e.target.disabled = true; try { const result = await api('legacy/import', pkg); document.querySelector('#legacy-result').textContent = `${result.imported} incorporados; ${result.preserved} conservados; ${result.conflicts.length} diferencias pendientes. ${JSON.stringify(result.conflicts)}`; notice('Migración registrada. Revisa las diferencias antes de usar los registros.'); } catch (error) { notice(error.message, true); e.target.disabled = false; } };
}
const templateNames = { 'TMPL-01': 'Nómina de matrícula', 'TMPL-02': 'Ficha de matrícula', 'TMPL-03': 'Registro de matrícula modular', 'TMPL-04': 'Portada docente', 'TMPL-18': 'Resumen de resultados', 'TMPL-19': 'Acta de evaluación modular', 'TMPL-20': 'Certificado', 'TMPL-21': 'Título' };
function profile(page) {
  page.innerHTML = heading('Mi cuenta', 'Tu identidad y permisos pertenecen a la cuenta asignada por dirección.') + `<div class="card"><h2>${escape(data.user.name)}</h2><p>${escape(data.user.username)} · ${escape(roleName[data.user.role])}</p><p class="muted">${data.status.authority ? 'Equipo institucional' : 'Autorización offline válida hasta ' + escape(new Date(data.status.validUntil).toLocaleDateString('es-PE'))}</p><form id="password-form"><div class="form-grid"><label>Contraseña actual<input name="currentPassword" type="password" autocomplete="current-password" required></label><label>Nueva contraseña<input name="password" type="password" minlength="8" autocomplete="new-password" required></label></div><p class="error" data-error></p><button type="submit" class="primary">Cambiar contraseña</button></form></div>`;
  bindForm('#password-form', async v => { const result=await api('password', v); token = null; sessionStorage.removeItem('CETPRO_LOCAL_TOKEN'); notice(result.pending?'Contraseña local actualizada. Ingresa y exporta tus cambios para sincronizarla con dirección.':'Contraseña actualizada. Ingresa nuevamente.'); await render(); });
}
async function render() {
  const version = ++routeVersion;
  try {
    if (!token) return await authScreen();
    data = await api('dashboard'); if (version !== routeVersion) return;
    let route = location.hash.replace('#/', '') || 'inicio';
    if ((['respaldo'].includes(route) && data.user.role !== 'DIRECTOR') || (route === 'matriculas' && data.user.role === 'DOCENTE')) { notice('Esta función no pertenece a tu cuenta.', true); route = 'inicio'; }
    if(!data.policy?.routes.includes(route)){notice('Esta función no pertenece a tu cuenta.',true);route='inicio';}
    shell(route); const page = document.querySelector('#page');
    switch (route) { case 'estudiantes': students(page); break; case 'matriculas': enrollments(page); break; case 'grupos': groups(page); break; case 'evaluacion': await renderGradeMatrix(page, {data,api,escape,heading,options,notice,render,setDirty:value=>dirty=value}); break; case 'asistencia': academic(page, 'attendance'); break; case 'cuentas': await accounts(page); break; case 'datos': await renderDataExchange(page,{data,api,escape,heading,options,notice,render}); break; case 'sincronizacion': await sync(page); break; case 'respaldo': await backup(page); break; case 'documentos': await renderDocuments(page,{data,api,escape,heading,options,notice,bindForm,render}); break; case 'configuracion-documental': await renderDocumentConfiguration(page,{data,api,escape,heading,options,notice,bindForm,render,setDirty:value=>dirty=value}); break; case 'entregas': await renderDeliveries(page,{data,api,escape,heading,options,notice,bindForm,render}); break; case 'perfil': profile(page); break; default: home(page); }
  } catch (e) { if (!token) await authScreen(); notice(e.message, true); }
}
root.addEventListener('click', event => { const link = event.target.closest('a[href^="#/"]'); if (link && dirty) { if (!confirm('Hay cambios sin guardar. ¿Salir de esta pantalla?')) event.preventDefault(); else dirty = false; } });
window.addEventListener('beforeunload', event => { if (dirty) { event.preventDefault(); event.returnValue = ''; } });
window.addEventListener('hashchange', () => { dirty = false; render(); });
render();
