const states=[['P','✓','Presente'],['T','◷','Tardanza'],['F','×','Falta'],['J','⊘','Justificada']];
export function avatarKind(student){const sex=String(student?.sex||student?.legacy?.sexo||'').trim().toUpperCase();return ['H','HOMBRE','MASCULINO'].includes(sex)?'male':['M','MUJER','FEMENINO'].includes(sex)?'female':'neutral';}
export function studentAvatar(student){const kind=avatarKind(student);return `<img class="student-avatar" src="/app/operational/assets/avatars/${kind}.svg" alt="${kind==='male'?'Alumno':kind==='female'?'Alumna':'Estudiante'}" width="44" height="44">`;}
export function installRollCall(page,{data,teacher,isDirty,markDirty}){
 const card=page.querySelector('#academic-group').closest('.card'),table=page.querySelector('#academic-rows').closest('.table-wrap'),actions=page.querySelector('#save-state').closest('.actions');
 const dialog=document.createElement('dialog');dialog.id='attendance-dialog';dialog.className='roll-dialog';dialog.setAttribute('aria-labelledby','roll-title');dialog.innerHTML='<header class="roll-header"><div><h2 id="roll-title">Llamada de lista</h2><p>Selecciona un estado por estudiante y guarda al terminar.</p></div><button type="button" id="roll-close" aria-label="Cerrar llamada de lista">×</button></header><div class="roll-context"></div><div class="roll-tools"><label>Buscar estudiante<input id="roll-search" type="search" placeholder="Nombre o DNI"></label><p id="roll-counts" role="status" aria-live="polite"></p></div><div class="roll-table"></div><footer class="roll-footer"></footer>';
 page.append(dialog);dialog.querySelector('.roll-table').append(table);dialog.querySelector('.roll-footer').append(actions);
 const all=page.querySelector('#all-present');if(all)dialog.querySelector('.roll-tools').append(all);
 const open=document.createElement('button');open.id='attendance-open';open.className='primary';open.textContent=teacher?'Pasar lista':'Consultar lista';card.append(open);
 const help=document.createElement('p');help.className='muted';help.textContent='La lista se abre en esta ventana. Puedes buscar estudiantes, revisar sus marcas y guardar los cambios.';card.append(help);
 open.onclick=()=>{const date=page.querySelector('#academic-date').value,unit=page.querySelector('#academic-unit').selectedOptions[0]?.textContent;dialog.querySelector('.roll-context').textContent=`${unit||'Unidad'} · ${date} · Sesión ${page.querySelector('#academic-session').value}`;dialog.showModal();dialog.querySelector('#roll-search').focus();refresh();};
 function close(){if(isDirty()&&!confirm('Hay cambios sin guardar. ¿Cerrar la lista y conservarlos para seguir después?'))return;dialog.close();open.focus();}
 dialog.querySelector('#roll-close').onclick=close;dialog.addEventListener('cancel',ev=>{ev.preventDefault();close();});
 function refresh(){dialog.querySelector('.roll-context').textContent=`${page.querySelector('#academic-unit').selectedOptions[0]?.textContent||'Unidad'} · ${page.querySelector('#academic-date').value} · Sesión ${page.querySelector('#academic-session').value}`;const rows=[...page.querySelectorAll('#academic-rows tr[data-enrollment]')],query=dialog.querySelector('#roll-search').value.trim().toLocaleLowerCase('es');let completed=0;
 for(const row of rows){const field=row.querySelector('.academic-value');if(field.value)completed++;row.hidden=!row.textContent.toLocaleLowerCase('es').includes(query);row.querySelectorAll('[data-mark]').forEach(b=>b.setAttribute('aria-pressed',String(field.value===b.dataset.mark)));const badge=row.querySelector('.roll-state');if(badge)badge.textContent=states.find(s=>s[0]===field.value)?.[2]||'Sin registrar';}
 dialog.querySelector('#roll-counts').textContent=`${completed} de ${rows.length} registrados · ${rows.length-completed} pendientes`;help.textContent=`${completed} de ${rows.length} estudiantes con marca en esta sesión. ${isDirty()?'Hay cambios sin guardar; abre la lista para guardarlos.':'Abre la lista para revisar los estados.'}`;
 }
 function enhance(){const tbody=page.querySelector('#academic-rows');table.querySelector('thead').innerHTML='<tr><th>Estudiante</th><th>Estado actual</th>'+states.map(s=>`<th>${s[2]}</th>`).join('')+'<th>Observación</th></tr>';
 for(const row of tbody.querySelectorAll('tr[data-enrollment]')){if(row.dataset.enhanced)continue;row.dataset.enhanced='true';const enrollment=data.enrollments.find(e=>e.id===row.dataset.enrollment),student=data.students.find(s=>s.id===enrollment?.studentId);row.cells[0].insertAdjacentHTML('afterbegin',studentAvatar(student));const field=row.querySelector('.academic-value'),stateCell=field.closest('td');stateCell.className='roll-current';field.classList.add('roll-value');stateCell.insertAdjacentHTML('beforeend','<span class="roll-state"></span>');
 for(const [value,symbol,label]of states){const cell=document.createElement('td'),button=document.createElement('button');button.type='button';button.className='roll-mark mark-'+value;button.dataset.mark=value;button.dataset.label=label;button.textContent=symbol;button.setAttribute('aria-label',label+' — '+(student?.name||'Estudiante'));button.disabled=field.disabled;button.onclick=()=>{field.value=field.value===value?'':value;field.dispatchEvent(new Event('input',{bubbles:true}));refresh();};cell.append(button);row.insertBefore(cell,row.lastElementChild);}
 const obs=row.querySelector('.academic-observation'),cell=obs.closest('td'),details=document.createElement('details'),summary=document.createElement('summary');summary.textContent='Añadir nota';details.append(summary,obs);cell.append(details);if(obs.value)details.open=true;
 }refresh();}
 const observer=new MutationObserver(enhance);observer.observe(page.querySelector('#academic-rows'),{childList:true});enhance();
 dialog.querySelector('#roll-search').oninput=refresh;table.addEventListener('input',()=>{markDirty();refresh();});if(all)all.addEventListener('click',refresh);
}
