const exampleFor=(key,type)=>({nombre:'Ej.: CETPRO Micaela Bastidas',codigoModular:'Ej.: código modular de siete cifras',dre:'Ej.: DRE Lima Metropolitana',ugel:'Ej.: UGEL correspondiente',hours:'Ej.: 120 horas',credits:'Ej.: 4 créditos',name:'Ej.: Procesador de textos',capacity:'Ej.: Elabora documentos de oficina según la tarea',indicator1:'Ej.: Identifica las herramientas de edición',registerCode:'Ej.: código del libro de registro',teacherName:'Ej.: nombres completos del docente responsable',fechaInicio:'AAAA-MM-DD',fechaFin:'AAAA-MM-DD'}[key]|| (type==='number'?'Ej.: 4':type==='date'?'AAAA-MM-DD':key.startsWith('indicator')?'Ej.: descripción del logro que evaluará':'Escriba el dato institucional correspondiente'));
const scopeNames={institution:'Institución',program:'Programa',module:'Módulo',group:'Grupo y periodo',unit:'Unidad: capacidades e indicadores',unitCurriculum:'Unidad: horas y créditos',enrollment:'Matrícula y expedición',registry:'Registro institucional',practice:'Evaluación EFSRT',closure:'Cierre modular'};
const fieldNames={students:'Ficha de estudiantes',enrollments:'Datos de matrícula',unit:'Datos de la unidad',units:'Plan de unidades',evaluation:'Registro de notas',attendance:'Registro de asistencia',efsrt:'Evaluación EFSRT',closure:'Cierre modular',document:'Datos registrales'};
let previewTask=null;
async function drawPDF(container,blob){
 const pdfjs=await import('./pdfjs/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='/app/operational/pdfjs/pdf.worker.mjs';
 const bytes=new Uint8Array(await blob.arrayBuffer()),task=pdfjs.getDocument({data:bytes,useSystemFonts:true});const pdf=await task.promise;let pageNumber=1,zoom=1,rendering=false;
 container.innerHTML='<div class="pdf-controls"><button data-prev type="button">← Anterior</button><span data-page></span><button data-next type="button">Siguiente →</button><label>Zoom<select data-zoom><option value="1">Ajustar</option><option value="1.25">125%</option><option value="1.5">150%</option><option value="2">200%</option></select></label></div><div class="pdf-stage"><canvas class="pdf-canvas" aria-label="Vista previa del documento institucional lleno"></canvas></div>';
 const canvas=container.querySelector('canvas'),status=container.querySelector('[data-page]');
 async function render(){if(rendering)return;rendering=true;try{const page=await pdf.getPage(pageNumber),base=page.getViewport({scale:1}),width=Math.max(300,container.clientWidth-38),viewport=page.getViewport({scale:width/base.width*zoom});canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;status.textContent=`Página ${pageNumber} de ${pdf.numPages}`;container.querySelector('[data-prev]').disabled=pageNumber===1;container.querySelector('[data-next]').disabled=pageNumber===pdf.numPages;}finally{rendering=false;}}
 container.querySelector('[data-prev]').onclick=async()=>{if(pageNumber>1&&!rendering){pageNumber--;await render();}};container.querySelector('[data-next]').onclick=async()=>{if(pageNumber<pdf.numPages&&!rendering){pageNumber++;await render();}};container.querySelector('[data-zoom]').onchange=async event=>{zoom=Number(event.target.value);await render();};await render();previewTask=task;
}
function downloadPDF(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export async function renderDocuments(page,ctx){
 const {data,api,escape:e,heading,options,notice}=ctx,configuration=await api('document/configuration'),names=Object.fromEntries(configuration.catalog.map(t=>[t.id,t.name]));let doc=null,blob=null,generation=0;
 page.innerHTML=heading(data.user.role==='DOCENTE'?'Mis documentos institucionales':'Documentos institucionales','Selecciona la plantilla. El llenado toma los datos de su grupo, unidad y matrícula.')+'<div class="subnav"><a class="button" href="#/configuracion-documental">Configurar datos de documentos</a><a class="button" href="#/entregas">Entregas y revisión</a></div>'+`<div class="card"><div class="toolbar"><label>Grupo<select id="document-group">${options(data.groups,null,g=>g.name+' · '+(g.periodId||'Periodo pendiente'))}</select></label><label>Plantilla institucional<select id="document-template"></select></label><label id="document-unit-label" hidden>Unidad de asistencia<select id="document-unit"></select></label><label id="document-enrollment-label">Estudiante / matrícula<select id="document-enrollment"></select></label><button id="document-generate" class="primary">Actualizar vista previa</button></div><p class="muted">El PDF se muestra con el formato institucional original. Los campos faltantes permanecen vacíos y se señalan aquí.</p></div><div class="document-workspace"><section class="card" id="document-checklist"><h2>Parámetros de la plantilla</h2><p class="muted">Actualiza la vista previa para comprobar su llenado.</p></section><section class="card"><div id="document-preview"><p class="empty">Selecciona un documento y actualiza su vista previa.</p></div><div class="actions"><button id="document-pdf" disabled>Descargar el PDF mostrado</button><button id="document-submit" class="primary" disabled>Entregar este documento</button><span id="document-state" class="save-state" role="status"></span></div></section></div>`;
 const selectedGroup=()=>data.groups.find(g=>g.id===document.querySelector('#document-group').value);
 const request=()=>({...(Number(document.querySelector('#document-template').value.slice(5))>=5&&Number(document.querySelector('#document-template').value.slice(5))<=10?{unit:document.querySelector('#document-unit').value}:{}),groupId:selectedGroup()?.id,templateId:document.querySelector('#document-template').value,...(['TMPL-02','TMPL-20','TMPL-21'].includes(document.querySelector('#document-template').value)?{enrollmentId:document.querySelector('#document-enrollment').value}:{})});
 function selectors(){const g=selectedGroup(),select=document.querySelector('#document-template'),previous=select.value,units=g?.units.filter(u=>u!=='EFSRT')||[];
  const allowed=data.templates.filter(t=>{if(data.user.role!=='DOCENTE')return true;const n=Number(t.slice(5)),unit=n>=5&&n<=10?units[n-5]:n>=11&&n<=17?units[n-11]:n===18?'EFSRT':null;return n===4||(n===5&&units.some(u=>data.user.assignments.some(a=>a.groupId===g?.id&&a.units.includes(u))))||(unit&&data.user.assignments.some(a=>a.groupId===g?.id&&a.units.includes(unit)));});
  select.innerHTML=allowed.map(t=>`<option value="${t}">${t} · ${e(names[t]||t)}</option>`).join('');if(allowed.includes(previous))select.value=previous;
  const attendance=Number(select.value.slice(5))>=5&&Number(select.value.slice(5))<=10,unitSelect=document.querySelector('#document-unit');document.querySelector('#document-unit-label').hidden=!attendance;unitSelect.innerHTML=units.filter(u=>data.user.role!=='DOCENTE'||data.user.assignments.some(a=>a.groupId===g?.id&&a.units.includes(u))).map(u=>`<option>${e(u)}</option>`).join('');const mapped=units[Number(select.value.slice(5))-5];if([...unitSelect.options].some(o=>o.value===mapped))unitSelect.value=mapped;
  const individual=['TMPL-02','TMPL-20','TMPL-21'].includes(select.value);document.querySelector('#document-enrollment-label').hidden=!individual;
  const roster=data.enrollments.filter(r=>r.groupId===g?.id&&r.active&&!data.students.find(s=>s.id===r.studentId)?.archived);document.querySelector('#document-enrollment').innerHTML=options(roster,null,r=>data.students.find(s=>s.id===r.studentId)?.name||r.id);
  document.querySelector('#document-generate').disabled=!g||!allowed.length||(individual&&!roster.length);invalidate();
 }
 function invalidate(){generation++;doc=null;blob=null;document.querySelector('#document-pdf').disabled=true;document.querySelector('#document-submit').disabled=true;document.querySelector('#document-state').textContent='Vista previa pendiente de actualizar.';}
 function checklist(){const report=doc.preflight;document.querySelector('#document-checklist').innerHTML=`<h2>${e(names[doc.templateId])}</h2><p><span class="badge">${report.filled}/${report.total} parámetros completos</span></p><p>${report.complete?'El documento tiene sus parámetros completos.':'Completa los campos pendientes antes de entregar.'}</p><div class="field-checklist">${report.fields.map(f=>`<div class="field-check ${f.status==='READY'?'ready':'missing'}"><strong>${f.status==='READY'?'✓':'○'} ${e(f.label||f.key)}</strong><small>${e(f.source)}</small><span>${f.status==='READY'?e(f.value):'Pendiente de completar'}</span></div>`).join('')}</div><a class="button" href="#/configuracion-documental">Completar datos comunes y parámetros</a>`;}
 document.querySelector('#document-group').onchange=selectors;document.querySelector('#document-template').onchange=selectors;document.querySelector('#document-enrollment').onchange=invalidate;document.querySelector('#document-unit').onchange=invalidate;selectors();let hint;try{hint=JSON.parse(sessionStorage.getItem('CETPRO_DOCUMENT_SELECTION')||'null');sessionStorage.removeItem('CETPRO_DOCUMENT_SELECTION');}catch{}if(hint&&data.groups.some(g=>g.id===hint.groupId)){document.querySelector('#document-group').value=hint.groupId;selectors();document.querySelector('#document-template').value='TMPL-05';selectors();if([...document.querySelector('#document-unit').options].some(o=>o.value===hint.unit))document.querySelector('#document-unit').value=hint.unit;}
 document.querySelector('#document-generate').onclick=async event=>{const version=++generation;event.target.disabled=true;blob=null;doc=null;document.querySelector('#document-pdf').disabled=true;document.querySelector('#document-submit').disabled=true;document.querySelector('#document-state').textContent='Preparando PDF institucional…';try{const next=await api('document',request());if(version!==generation)return;doc=next;checklist();const pdf=await api('document/pdf',{...request(),fingerprint:next.fingerprint});if(version!==generation)return;blob=pdf;await drawPDF(document.querySelector('#document-preview'),blob);document.querySelector('#document-pdf').disabled=false;document.querySelector('#document-submit').disabled=!doc.preflight.complete;document.querySelector('#document-state').textContent=doc.preflight.complete?'Vista previa actualizada. Lista para entregar.':'Vista previa actualizada con campos pendientes.';}catch(error){notice(error.message,true);document.querySelector('#document-state').textContent=error.message;}finally{if(event.target.isConnected)event.target.disabled=false;}};
 document.querySelector('#document-pdf').onclick=()=>blob&&downloadPDF(blob,`${doc.templateId}_${doc.group.id}_COMPLETADO.pdf`);
 document.querySelector('#document-submit').onclick=async event=>{if(!doc||!blob)return;event.target.disabled=true;try{const submission=await api('document/submit',{...request(),fingerprint:doc.fingerprint});document.querySelector('#document-state').textContent=`Documento entregado y conservado: ${submission.id.slice(0,8)}. Sincroniza para que llegue al equipo institucional.`;notice('Entrega registrada con copia exacta del PDF y sus parámetros.');}catch(error){notice(error.message,true);event.target.disabled=false;}};
}
export async function renderDocumentConfiguration(page,ctx){
 const {data,api,escape:e,heading,options,notice}=ctx,config=await api('document/configuration');
 page.innerHTML=heading('Datos y parámetros de documentos','Se guardan una vez y se reutilizan según el documento y la cuenta.')+`<div class="card"><div class="toolbar"><label>Datos a configurar<select id="parameter-kind">${Object.entries(scopeNames).filter(([key])=>config.schema[key]).map(([key,name])=>`<option value="${key}">${name}</option>`).join('')}</select></label><label id="parameter-group-label">Grupo<select id="parameter-group">${options(data.groups,null,g=>g.name+' · '+(g.periodId||'Pendiente'))}</select></label><label id="parameter-target-label">Destino<select id="parameter-target"></select></label><label id="parameter-unit-label">Unidad<select id="parameter-unit"></select></label></div><p class="section-note">Solo se habilitan los campos que puedes modificar. Los valores son los de la institución y su plan; el sistema no inventa horas, créditos ni resultados.</p><form id="parameters-form"><div class="form-grid" id="parameter-fields"></div><div class="actions"><button type="submit" class="primary" id="save-parameters">Guardar parámetros</button><a class="button" href="#/documentos">Ver documento lleno</a></div><p class="error" data-error></p></form></div>`;
 const kind=document.querySelector('#parameter-kind'),groupSelect=document.querySelector('#parameter-group'),target=document.querySelector('#parameter-target'),unit=document.querySelector('#parameter-unit');if(data.user.role==='DOCENTE')kind.value='unit';
 let scope,current,defaults={},formDirty=false;const previous=new Map();
 function prepareTargets(){const k=kind.value,g=data.groups.find(g=>g.id===groupSelect.value);document.querySelector('#parameter-group-label').hidden=['institution','program','module'].includes(k);document.querySelector('#parameter-target-label').hidden=['institution','group','unit','unitCurriculum'].includes(k);document.querySelector('#parameter-unit-label').hidden=!['unit','unitCurriculum'].includes(k);
  target.innerHTML=['enrollment','registry','practice','closure'].includes(k)?options(data.enrollments.filter(r=>r.groupId===g?.id),null,r=>data.students.find(s=>s.id===r.studentId)?.name||r.id):k==='program'?options(data.programs,null,p=>p.nombre):k==='module'?options(data.modules,null,m=>m.nombre):'';
  unit.innerHTML=(g?.units.filter(u=>u!=='EFSRT'&&(data.user.role!=='DOCENTE'||data.user.assignments.some(a=>a.groupId===g.id&&a.units.includes(u))))||[]).map(u=>`<option>${e(u)}</option>`).join('');draw();
 }
 function draw(){const k=kind.value;scope={kind:k,...(k==='institution'?{}:{target:['group','unit','unitCurriculum'].includes(k)?groupSelect.value:target.value}),...(['unit','unitCurriculum'].includes(k)?{unit:unit.value}:{})};const id=`${k}:${scope.target||'institution'}${scope.unit?':'+scope.unit:''}`;current=config.settings.find(s=>s.id===id);defaults={...(config.defaults?.[id]||{}),...(current?.fields||{})};
  const practiceAllowed=k!=='practice'||data.user.role!=='DOCENTE'||data.user.assignments.some(a=>a.groupId===groupSelect.value&&a.units.includes('EFSRT'));const canEdit=practiceAllowed&&(config.schema[k]||[]).some(f=>f.roles.includes(data.user.role));document.querySelector('#save-parameters').disabled=!canEdit||(k!=='institution'&&!scope.target)||(['unit','unitCurriculum'].includes(k)&&!scope.unit);
  document.querySelector('#parameter-fields').innerHTML=(config.schema[k]||[]).map(f=>{const value=defaults[f.key]??(k==='institution'&&f.key==='nombre'?data.status.institutionName:''),disabled=!practiceAllowed||!f.roles.includes(data.user.role);return `<label class="${f.type==='textarea'?'wide':''}">${e(f.label)}${f.type==='textarea'?`<textarea name="${f.key}" placeholder="${e(exampleFor(f.key,f.type))}"${disabled?' disabled':''}>${e(value)}</textarea>`:f.type==='select'?`<select name="${f.key}"${disabled?' disabled':''}><option value="">Sin configurar</option>${f.options.map(v=>`<option value="${e(v)}"${value===v?' selected':''}>${e(v)}</option>`).join('')}</select>`:`<input name="${f.key}" type="${f.type==='number'?'number':f.type==='date'?'date':'text'}"${f.type==='number'?' min="0" step="0.01"':''} placeholder="${e(exampleFor(f.key,f.type))}" value="${e(value)}"${disabled?' disabled':''}>`}</label>`;}).join('');
 }
 for(const control of [kind,groupSelect,target,unit]){previous.set(control,control.value);control.onchange=()=>{if(formDirty&&!confirm('Hay parámetros sin guardar. ¿Cambiar el contexto?')){control.value=previous.get(control);return;}formDirty=false;ctx.setDirty?.(false);(control===kind||control===groupSelect?prepareTargets:draw)();for(const c of [kind,groupSelect,target,unit])previous.set(c,c.value);};}prepareTargets();document.querySelector('#parameters-form').oninput=()=>{formDirty=true;ctx.setDirty?.(true);};
 ctx.bindForm('#parameters-form',async(v)=>{const fields={};for(const f of (config.schema[kind.value]||[]).filter(f=>f.roles.includes(data.user.role)))fields[f.key]=f.type==='number'&&v[f.key]!==''?Number(v[f.key]):v[f.key]||'';const result=await api('document/configuration',{scope,fields,rev:current?.rev||null});const index=config.settings.findIndex(r=>r.id===result.id);index<0?config.settings.push(result):config.settings[index]=result;formDirty=false;ctx.setDirty?.(false);draw();notice('Parámetros guardados. Se aplicarán a la siguiente vista previa y se podrán sincronizar.');});
}
export async function renderDeliveries(page,ctx){
 const {data,api,escape:e,heading,notice}=ctx,rows=data.submissions||[];
 page.innerHTML=heading(data.user.role==='DOCENTE'?'Mis entregas':'Recepción y revisión de documentos','Cada entrega conserva el PDF exacto y los parámetros usados al generarlo.')+`<div class="card"><div class="table-wrap"><table><thead><tr><th>Documento</th><th>Autor / grupo</th><th>Estado</th><th>Revisión</th><th>Acciones</th></tr></thead><tbody>${rows.map(s=>`<tr><td>${e(s.templateId)}<small>${e(new Date(s.createdAt).toLocaleString('es-PE'))}</small></td><td>${e(s.authorName)}<small>${e(s.groupId)}</small></td><td>${e(s.status)}</td><td>${e(s.reviewReason||'Pendiente')}</td><td><button data-preview="${e(s.id)}" class="small">Ver PDF entregado</button>${data.user.role!=='DOCENTE'?`<button data-review="${e(s.id)}" class="small">Revisar</button>`:''}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No hay documentos entregados.</td></tr>'}</tbody></table></div></div><div class="card" id="delivery-preview" hidden></div>`;
 page.querySelectorAll('[data-preview]').forEach(button=>button.onclick=async()=>{try{const box=document.querySelector('#delivery-preview');box.hidden=false;await drawPDF(box,await api('document/submission-pdf',{id:button.dataset.preview}));box.scrollIntoView({behavior:'smooth'});}catch(error){notice(error.message,true);}});
 page.querySelectorAll('[data-review]').forEach(button=>button.onclick=async()=>{const row=rows.find(r=>r.id===button.dataset.review),status=prompt(data.user.role==='DIRECTOR'?'Estado: RECIBIDO, OBSERVADO o REVISADO':'Estado: RECIBIDO u OBSERVADO');if(!status)return;const reason=prompt('Detalle de recepción u observación:');if(!reason)return;try{await api('document/review',{id:row.id,rev:row.rev,status:status.trim().toUpperCase(),reason});notice('Revisión registrada. La emisión oficial conserva sus validaciones independientes.');await ctx.render();}catch(error){notice(error.message,true);}});
}
