export async function renderPortableExchange(page,{data,api,escape:e,options,notice,render}){
 const advanced=document.createElement('details');advanced.className='card';advanced.innerHTML='<summary>Vinculación de equipos y envío a un destinatario específico</summary>';for(const child of [...page.children])if(!child.classList.contains('page-head'))advanced.append(child);page.append(advanced);
 const panel=document.createElement('section');panel.className='card';panel.innerHTML=`<h2>Exportar y recibir la base de mis grupos</h2><p>Funciona mediante archivo y USB. Exporta las aulas permitidas, notas, asistencia y cambios administrativos. Recibir un archivo actualiza los registros modificados y conserva los demás.</p><div class="form-grid"><label>Grupo a exportar<select id="exchange-group"><option value="">Todos mis grupos permitidos</option>${options(data.groups,null,g=>g.name)}</select></label><label>Clave del archivo de intercambio<input id="exchange-key" type="password" minlength="8" autocomplete="off" placeholder="Ej.: Aula2026!Computacion"><small>Utiliza la misma clave al recibir el archivo. No es la contraseña de inicio de sesión.</small></label></div>${data.user.role!=='DOCENTE'?'<label><input id="exchange-accounts" type="checkbox"> Incluir solicitudes y cambios de usuarios (archivo para dirección o secretaría)</label>':''}<button id="exchange-export" class="primary">Exportar base para intercambio (.cetpro)</button><hr><h2>Recibir una actualización</h2><p>Los equipos deben estar vinculados a la misma institución. Puedes recibir el trabajo del docente en secretaría y devolverle las matrículas nuevas, sin sustituir la base.</p><label>Archivo de actualización<input id="exchange-file" type="file" accept=".cetpro,.json"></label><div class="actions"><button id="exchange-preview">Revisar archivo sin cambiar datos</button><button id="exchange-apply" class="primary" disabled>Aplicar actualización revisada</button></div><div id="exchange-result" role="status"></div><p class="muted">Se crea una copia antes de aplicar. Si dos equipos cambiaron el mismo registro, se conservan ambas versiones para revisión por dirección.</p>`;page.insertBefore(panel,advanced);
 let pkg=null,reviewed=false;const key=()=>panel.querySelector('#exchange-key').value,result=panel.querySelector('#exchange-result'),apply=panel.querySelector('#exchange-apply');
 const invalidate=()=>{reviewed=false;apply.disabled=true;};panel.querySelector('#exchange-key').oninput=invalidate;panel.querySelector('#exchange-file').onchange=()=>{pkg=null;invalidate();result.textContent='Archivo pendiente de revisión.';};
 panel.querySelector('#exchange-export').onclick=async event=>{event.target.disabled=true;try{const value=await api('exchange/export',{groupId:panel.querySelector('#exchange-group').value||undefined,passphrase:key(),includeAccounts:!!panel.querySelector('#exchange-accounts')?.checked}),blob=new Blob([JSON.stringify(value)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='BASE_GRUPOS_CETPRO_'+data.user.username+'.cetpro';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);result.textContent='Archivo exportado. Lleva el archivo y comunica la clave al destinatario.';notice('Base de grupos exportada.');}catch(err){notice(err.message,true);result.textContent=err.message;}finally{event.target.disabled=false;}};
 panel.querySelector('#exchange-preview').onclick=async()=>{invalidate();try{const file=panel.querySelector('#exchange-file').files[0];if(!file||file.size>32*1024*1024)throw Error('Seleccione un archivo CETPRO de hasta 32 MB.');pkg=JSON.parse(await file.text());const report=await api(pkg.body?.type==='GROUP_EXCHANGE'?'exchange/preview':'sync/preview',{package:pkg,passphrase:key()});result.innerHTML=`<p><strong>${report.newRecords} registros nuevos · ${report.updates} actualizaciones · ${report.duplicates} ya recibidos</strong></p><p>${report.conflicts} conflictos conservados · ${report.pending} dependencias pendientes</p>${report.duplicatePackage?'<p>El archivo ya fue recibido.</p>':''}`;reviewed=!report.duplicatePackage;apply.disabled=!reviewed;}catch(err){pkg=null;result.textContent=err.message;notice(err.message,true);}};
 apply.onclick=async()=>{if(!pkg||!reviewed)return;apply.disabled=true;try{const report=await api(pkg.body?.type==='GROUP_EXCHANGE'?'exchange/import':'sync/import',{package:pkg,passphrase:key()});notice(`Recibidos ${report.newRecords} nuevos y ${report.updates} cambios; ${report.conflicts} conflictos conservados.`);await render();}catch(err){result.textContent=err.message;notice(err.message,true);invalidate();}};
}
