export async function renderGradeMatrix(page,ctx){
 const {data,api,escape:e,heading,options,notice}=ctx,teacher=data.user.role==='DOCENTE';
 const stored=sessionStorage.getItem('CETPRO_grades_GROUP'),group=data.groups.find(g=>g.id===stored)||data.groups[0];if(!group){page.innerHTML=heading('Registro de evaluación','Dirección debe asignar un grupo y sus unidades.');return;}
 const units=group.units.filter(u=>u!=='EFSRT'&&(!teacher||data.user.assignments.some(a=>a.groupId===group.id&&a.units.includes(u))));
 page.innerHTML=heading('Registro auxiliar de evaluación','La matriz corresponde a los cinco indicadores de las plantillas institucionales.')+`<div class="subnav"><a class="button" href="#/configuracion-documental">Capacidad e indicadores</a><a class="button" href="#/documentos">Vista previa del documento</a></div><div class="card"><div class="toolbar"><label>Grupo<select id="academic-group">${options(data.groups,group.id,g=>g.name)}</select></label><label>Unidad<select id="academic-unit">${units.map(u=>`<option>${e(u)}</option>`).join('')}</select></label></div><p class="muted">IA1, IA2 e IA3: instrumentos de evaluación · IL: calificación del indicador · R: recuperación, si corresponde. Logro: resultado confirmado de la unidad. Celdas vacías: pendientes; cero: nota registrada.</p><div id="unit-description" class="section-note"></div><div class="table-wrap"><table class="grade-matrix"><thead><tr><th rowspan="2">Estudiante</th>${Array.from({length:5},(_,i)=>`<th colspan="5">Indicador de logro ${i+1}</th>`).join('')}<th rowspan="2">Logro UD</th></tr><tr>${Array.from({length:5},()=>['IA1','IA2','IA3','IL','R'].map(c=>`<th>${c}</th>`).join('')).join('')}</tr></thead><tbody id="academic-rows"></tbody></table></div><div class="actions">${teacher?'<button id="save-academic" class="primary">Guardar matriz</button>':''}<span id="save-state" class="save-state" role="status">Sin cambios pendientes.</span></div></div>`;
 let dirty=false,map=new Map(),configuration=await api('document/configuration');
 const indicators=Array.from({length:5},(_,i)=>['IA1','IA2','IA3','','RECOVERY'].map(c=>`IL${i+1}${c?'.'+c:''}`)).flat().concat('RESULTADO_UD');
 function draw(){map=new Map();const unit=document.querySelector('#academic-unit').value,cfg=configuration.settings.find(s=>s.scope.kind==='unit'&&s.scope.target===group.id&&s.scope.unit===unit)?.fields||{};document.querySelector('#unit-description').innerHTML=`<strong>${e(cfg.name||unit||'Unidad pendiente')}</strong><p>${e(cfg.capacity||'Completa la capacidad y los indicadores en Configuración de documentos.')}</p>${Array.from({length:5},(_,i)=>`<small>IL${i+1}: ${e(cfg['indicator'+(i+1)]||'Descripción pendiente')}</small>`).join('<br>')}`;
  const roster=data.enrollments.filter(r=>r.groupId===group.id&&r.active).sort((a,b)=>(data.students.find(s=>s.id===a.studentId)?.name||'').localeCompare(data.students.find(s=>s.id===b.studentId)?.name||'','es'));
  document.querySelector('#academic-rows').innerHTML=roster.map(r=>`<tr data-enrollment="${e(r.id)}"><td class="student">${e(data.students.find(s=>s.id===r.studentId)?.name)}</td>${indicators.map(indicator=>{const value=data.grades.find(v=>v.enrollmentId===r.id&&v.unit===unit&&v.indicator===indicator);map.set(r.id+'|'+indicator,value||null);return `<td><input class="academic-value matrix-score" data-indicator="${indicator}" type="number" min="0" max="20" step="0.01" value="${e(value?.value)}" aria-label="${e(indicator)} de ${e(data.students.find(s=>s.id===r.studentId)?.name)}"${!teacher||group.closed||!unit?' disabled':''}></td>`;}).join('')}</tr>`).join('')||'<tr><td colspan="27" class="empty">Sin matrículas activas.</td></tr>';dirty=false;ctx.setDirty(false);
 }
 draw();let previousUnit=document.querySelector('#academic-unit').value;document.querySelector('#academic-rows').oninput=()=>{dirty=true;ctx.setDirty(true);document.querySelector('#save-state').textContent='Cambios sin guardar.';};
 document.querySelector('#academic-rows').onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();const column=[...document.querySelectorAll(`input[data-indicator="${event.target.dataset.indicator}"]:not(:disabled)`)],i=column.indexOf(event.target);column[i+1]?.focus();}};
 document.querySelector('#academic-group').onchange=async event=>{if(dirty&&!confirm('Hay cambios sin guardar. ¿Cambiar de grupo?')){event.target.value=group.id;return;}ctx.setDirty(false);sessionStorage.setItem('CETPRO_grades_GROUP',event.target.value);await ctx.render();};document.querySelector('#academic-unit').onchange=event=>{if(dirty&&!confirm('Hay cambios sin guardar. ¿Cambiar de unidad?')){event.target.value=previousUnit;return;}previousUnit=event.target.value;draw();};
 const save=document.querySelector('#save-academic');if(save)save.onclick=async()=>{const rows=[...document.querySelectorAll('.matrix-score:not(:disabled)')].map(field=>{const enrollmentId=field.closest('tr').dataset.enrollment,indicator=field.dataset.indicator,old=map.get(enrollmentId+'|'+indicator),value=field.value===''?null:Number(field.value);return {enrollmentId,indicator,value,rev:old?.rev||null,clear:value===null&&old?.value!=null,changed:(value!==null||old?.value!=null)&&value!==old?.value};}).filter(r=>r.changed);if(!rows.length){notice('Sin cambios para guardar.');return;}if(rows.some(r=>r.clear)&&!confirm('Algunas notas quedarán pendientes. Se conserva su historial. ¿Continuar?'))return;save.disabled=true;try{const result=await api('grades',{groupId:group.id,unit:document.querySelector('#academic-unit').value,rows});for(const r of result){const i=data.grades.findIndex(v=>v.id===r.id);i<0?data.grades.push(r):data.grades[i]=r;}draw();document.querySelector('#save-state').textContent=`Guardado en este equipo · ${result.length} celdas. Pendiente de sincronizar.`;notice('Matriz guardada sin modificar otras unidades ni estudiantes.');}catch(error){notice(error.message,true);document.querySelector('#save-state').textContent='No se guardó: '+error.message;}finally{save.disabled=false;}};
}
