import {unitGuide} from './unit-guide.js';
export async function renderGradeMatrix(page,ctx){
 const {data,api,escape:e,heading,options,notice}=ctx,teacher=data.user.role==='DOCENTE';
 const stored=sessionStorage.getItem('CETPRO_grades_GROUP'),group=data.groups.find(g=>g.id===stored)||data.groups[0];if(!group){page.innerHTML=unitGuide(data,'evaluacion')+heading('Registro de evaluación','Dirección debe asignar un grupo y sus unidades.');return;}
 const units=group.units.filter(u=>u!=='EFSRT'&&(!teacher||data.user.assignments.some(a=>a.groupId===group.id&&a.units.includes(u)))).filter(u=>!data.workspace?.unit||u===data.workspace.unit);
 page.innerHTML=unitGuide(data,'evaluacion')+heading('Registro auxiliar de evaluación','Trabaja un indicador a la vez. Los registros alimentan el formato institucional de evaluación.')+`<div class="subnav"><a class="button" href="#/configuracion-documental">Capacidad e indicadores</a><a class="button" href="#/documentos">Vista previa del documento</a></div><div class="card"><div class="toolbar"><label>Grupo<select id="academic-group">${options(data.groups,group.id,g=>g.name)}</select></label><label>Unidad<select id="academic-unit">${units.map(u=>`<option>${e(u)}</option>`).join('')}</select></label></div><p class="muted">IA1, IA2 e IA3: instrumentos de evaluación · IL: calificación del indicador · R: recuperación, si corresponde. Logro: resultado confirmado de la unidad. Celdas vacías: pendientes; cero: nota registrada.</p><details class="section-note"><summary>Consultar capacidad y los cinco indicadores</summary><div id="unit-description"></div></details><div class="indicator-tabs" role="group" aria-label="Indicador a evaluar"><button type="button" data-grade-tab="1" aria-pressed="true">Indicador 1</button><button type="button" data-grade-tab="2" aria-pressed="false">Indicador 2</button><button type="button" data-grade-tab="3" aria-pressed="false">Indicador 3</button><button type="button" data-grade-tab="4" aria-pressed="false">Indicador 4</button><button type="button" data-grade-tab="5" aria-pressed="false">Indicador 5</button><button type="button" data-grade-tab="6">Resultado de la unidad</button><button type="button" data-grade-tab="0">Ver matriz completa</button></div><p id="indicator-help" class="section-note"></p><div class="table-wrap"><table class="grade-matrix"><thead><tr><th rowspan="2">Estudiante</th>${Array.from({length:5},(_,i)=>`<th colspan="5">Indicador de logro ${i+1}</th>`).join('')}<th rowspan="2">Logro UD</th></tr><tr>${Array.from({length:5},()=>['IA1','IA2','IA3','IL','R'].map(c=>`<th>${c}</th>`).join('')).join('')}</tr></thead><tbody id="academic-rows"></tbody></table></div><div class="actions">${teacher?'<button id="save-academic" class="primary">Guardar matriz</button>':''}<span id="save-state" class="save-state" role="status">Sin cambios pendientes.</span></div></div>`;
 let activeIndicator=1;let dirty=false,map=new Map(),configuration=await api('document/configuration');if(!page.isConnected)return;
 const indicators=Array.from({length:5},(_,i)=>['IA1','IA2','IA3','','RECOVERY'].map(c=>`IL${i+1}${c?'.'+c:''}`)).flat().concat('RESULTADO_UD');
 function draw(){map=new Map();const unit=document.querySelector('#academic-unit').value,cfg={...(configuration.defaults['unit:'+group.id+':'+unit]||{}),...configuration.settings.find(s=>s.scope.kind==='unit'&&s.scope.target===group.id&&s.scope.unit===unit)?.fields||{}};document.querySelector('#unit-description').innerHTML=`<strong>${e(cfg.name||unit||'Unidad pendiente')}</strong><p>${e(cfg.capacity||'Completa la capacidad y los indicadores en Configuración de documentos.')}</p>${Array.from({length:5},(_,i)=>`<small>IL${i+1}: ${e(cfg['indicator'+(i+1)]||'Descripción pendiente')}</small>`).join('<br>')}`;
  const roster=data.enrollments.filter(r=>r.groupId===group.id&&r.active).sort((a,b)=>(data.students.find(s=>s.id===a.studentId)?.name||'').localeCompare(data.students.find(s=>s.id===b.studentId)?.name||'','es'));
  document.querySelector('#academic-rows').innerHTML=roster.map(r=>`<tr data-enrollment="${e(r.id)}"><td class="student">${e(data.students.find(s=>s.id===r.studentId)?.name)}</td>${indicators.map(indicator=>{const value=data.grades.find(v=>v.enrollmentId===r.id&&v.unit===unit&&v.indicator===indicator);map.set(r.id+'|'+indicator,value||null);return `<td><input class="academic-value matrix-score" data-indicator="${indicator}" type="number" min="0" max="20" step="0.01" value="${e(value?.value)}" aria-label="${e(indicator)} de ${e(data.students.find(s=>s.id===r.studentId)?.name)}"${!teacher||group.closed||!unit?' disabled':''}></td>`;}).join('')}</tr>`).join('')||'<tr><td colspan="27" class="empty">Sin matrículas activas.</td></tr>';dirty=false;ctx.setDirty(false);showIndicator();
 }
 function showIndicator(){
  const table=page.querySelector('.grade-matrix'),headers=table.tHead.rows;
  [...headers[0].cells].forEach((cell,i)=>cell.hidden=i>0&&(activeIndicator!==0&&(i!==activeIndicator)));
  [...headers[1].cells].forEach((cell,i)=>cell.hidden=activeIndicator!==0&&(Math.floor(i/5)+1!==activeIndicator));
  for(const row of table.tBodies[0].rows){if(!row.dataset.enrollment)continue;[...row.cells].forEach((cell,i)=>cell.hidden=i>0&&activeIndicator!==0&&(i===26?activeIndicator!==6:Math.floor((i-1)/5)+1!==activeIndicator));}
  table.classList.toggle('grade-focused',activeIndicator!==0);
  page.querySelectorAll('[data-grade-tab]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.gradeTab)===activeIndicator)));
  const unit=page.querySelector('#academic-unit').value,cfg={...(configuration.defaults['unit:'+group.id+':'+unit]||{}),...configuration.settings.find(s=>s.scope.kind==='unit'&&s.scope.target===group.id&&s.scope.unit===unit)?.fields||{}};
  page.querySelector('#indicator-help').textContent=activeIndicator===6?'Confirma el resultado final de la unidad según los criterios institucionales. El sistema no inventa promedios ni calificaciones.':activeIndicator===0?'Vista completa del formato. Puedes volver a un indicador sin perder lo que escribiste.':`Indicador ${activeIndicator}: ${cfg['indicator'+activeIndicator]||'Define su descripción en Preparar la unidad.'}`;
 }
 page.querySelectorAll('[data-grade-tab]').forEach(button=>button.onclick=()=>{activeIndicator=Number(button.dataset.gradeTab);showIndicator();});
 draw();if(data.workspace?.mode==='UNIT'){const option=page.querySelector('#academic-unit').selectedOptions[0];option.value=option.textContent;option.textContent=page.querySelector('#unit-description strong').textContent;page.querySelector('#academic-group').closest('label').hidden=true;}let previousUnit=document.querySelector('#academic-unit').value;document.querySelector('#academic-rows').oninput=()=>{dirty=true;ctx.setDirty(true);document.querySelector('#save-state').textContent='Cambios sin guardar.';};
 document.querySelector('#academic-rows').onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();const column=[...document.querySelectorAll(`input[data-indicator="${event.target.dataset.indicator}"]:not(:disabled)`)].filter(f=>f.getClientRects().length),i=column.indexOf(event.target);column[i+1]?.focus();}};
 document.querySelector('#academic-group').onchange=async event=>{if(dirty&&!confirm('Hay cambios sin guardar. ¿Cambiar de grupo?')){event.target.value=group.id;return;}ctx.setDirty(false);sessionStorage.setItem('CETPRO_grades_GROUP',event.target.value);await ctx.render();};document.querySelector('#academic-unit').onchange=event=>{if(dirty&&!confirm('Hay cambios sin guardar. ¿Cambiar de unidad?')){event.target.value=previousUnit;return;}previousUnit=event.target.value;draw();};
 const save=document.querySelector('#save-academic');if(save)save.onclick=async()=>{const rows=[...document.querySelectorAll('.matrix-score:not(:disabled)')].map(field=>{const enrollmentId=field.closest('tr').dataset.enrollment,indicator=field.dataset.indicator,old=map.get(enrollmentId+'|'+indicator),value=field.value===''?null:Number(field.value);return {enrollmentId,indicator,value,rev:old?.rev||null,clear:value===null&&old?.value!=null,changed:(value!==null||old?.value!=null)&&value!==old?.value};}).filter(r=>r.changed);if(!rows.length){dirty=false;ctx.setDirty(false);document.querySelector('#save-state').textContent='Sin cambios pendientes.';notice('Sin cambios para guardar.');return;}if(rows.some(r=>r.clear)&&!confirm('Algunas notas quedarán pendientes. Se conserva su historial. ¿Continuar?'))return;save.disabled=true;try{const result=await api('grades',{groupId:group.id,unit:document.querySelector('#academic-unit').value,rows});if(!page.isConnected)return;for(const r of result){const i=data.grades.findIndex(v=>v.id===r.id);i<0?data.grades.push(r):data.grades[i]=r;}draw();document.querySelector('#save-state').textContent=`Guardado en este equipo · ${result.length} celdas. Pendiente de sincronizar.`;notice('Matriz guardada sin modificar otras unidades ni estudiantes.');}catch(error){notice(error.message,true);document.querySelector('#save-state').textContent='No se guardó: '+error.message;}finally{save.disabled=false;}};
}
