import {secretariatGuide} from './secretariat-guide.js';
import {chooseWorkspace} from './workspace.js';
import {artwork,imageCredits} from './unit-presentation.js';
export async function chooseSecretariat(root,{api,escape:e,onSelected,onLogout}){
 const catalog=await api('workspace/options'),years=[...(catalog.years||new Set(catalog.groups.map(g=>g.year)))].sort().reverse();let year=years.find(y=>/^\d{4}$/.test(y))||years[0]||'',query='';
 function draw(){const groups=catalog.groups.filter(g=>g.year===year),careers=catalog.programs.filter(p=>groups.some(g=>g.programId===p.id)||!catalog.groups.some(g=>g.programId===p.id));root.innerHTML=`<main class="workspace-picker secretary-picker">${secretariatGuide('',true)}<div class="eyebrow">SECRETARÍA ACADÉMICA</div><h1>¿Qué carrera vas a gestionar?</h1><p>Elige una carrera. Después selecciona el módulo y el grupo con el que trabajarás.</p><div class="card toolbar"><label>Año lectivo<select id="secretary-year">${years.map(y=>`<option ${y===year?'selected':''}>${e(y)}</option>`).join('')}</select></label><label>Buscar carrera<input id="secretary-search" type="search" placeholder="Ej.: Computación, Peluquería…" value="${e(query)}"></label></div><div class="secretary-careers">${careers.map(p=>{const gs=groups.filter(g=>g.programId===p.id),art=artwork({name:p.nombre},p.nombre),count=catalog.stats?.find(s=>s.year===year&&s.programId===p.id)?.students||0;return `<article class="card secretary-career" data-career-name="${e(p.nombre.toLocaleLowerCase('es'))}"><img src="${art.src}" alt="" width="70" height="70"><h2>${e(p.nombre)}</h2><p>${gs.length} ${gs.length===1?'grupo':'grupos'} · ${count} ${count===1?'estudiante':'estudiantes'}</p><button class="primary" data-career="${e(p.id)}"${gs.length?'':' disabled'}>${gs.length?'Gestionar esta carrera':'Sin grupos en este año'}</button></article>`;}).join('')}</div><p id="secretary-no-results" hidden>No hay carreras que coincidan con la búsqueda.</p><section class="card secretary-general"><h2>Gestión general</h2><p>Usuarios docentes, recepción de archivos de distintas carreras y consultas institucionales.</p><button id="secretary-general">Abrir gestión general</button></section><button id="secretary-logout">Cerrar sesión</button>${imageCredits}</main>`;
 root.querySelector('[data-secretary-guide-context]').onclick=()=>root.querySelector('#secretary-search').focus();root.querySelector('#secretary-year').onchange=ev=>{year=ev.target.value;draw();};const search=root.querySelector('#secretary-search');function filter(){let count=0;root.querySelectorAll('[data-career-name]').forEach(card=>{card.hidden=!card.dataset.careerName.includes(query.toLocaleLowerCase('es'));if(!card.hidden)count++;});root.querySelector('#secretary-no-results').hidden=!!count;}search.oninput=ev=>{query=ev.target.value;filter();};filter();root.querySelector('#secretary-logout').onclick=onLogout;
 root.querySelector('#secretary-general').onclick=async()=>{await api('workspace',{overview:true});await onSelected();};root.querySelectorAll('[data-career]').forEach(b=>b.onclick=()=>chooseWorkspace(root,{api,escape:e,onSelected,onLogout,role:'SECRETARIA',initial:{year,program:b.dataset.career},onBack:draw}));
 }draw();
}
export function renderSecretariatHome(page,{data,escape:e,heading,onUnits}){const c=data.workspace,g=data.groups.find(g=>g.id===c?.groupId),general=!c||c.overview;
 const actions=general?[['cuentas','Registrar docentes','Crear o actualizar cuentas y asignar sus aulas.'],['sincronizacion','Recibir y enviar datos','Revisar archivos de distintas carreras y distribuir actualizaciones.'],['entregas','Recepción de documentos','Consultar las entregas institucionales.']]:c.mode==='UNIT'||c.mode==='PRACTICE'?[['asistencia','Consultar asistencia','Revisar las sesiones registradas por el docente.'],['evaluacion','Consultar evaluación','Revisar las notas de la unidad seleccionada.'],['documentos','Documentos de esta unidad','Ver los formatos disponibles y sus datos pendientes.'],['entregas','Entregas de esta unidad','Consultar recepción y observaciones.']].filter(([route])=>c.mode!=='PRACTICE'||!['asistencia','evaluacion'].includes(route)):[['estudiantes','Estudiantes','Buscar y actualizar estudiantes del grupo.'],['matriculas','Matrículas','Matricular estudiantes y corregir su participación en el módulo.'],['grupos','Organización del grupo','Revisar sección, turno, modalidad y docente.'],['documentos','Documentos del módulo','Preparar nóminas, fichas y otros formatos autorizados.'],['entregas','Recibir documentos docentes','Revisar las entregas del grupo seleccionado.'],['sincronizacion','Actualizar los equipos','Recibir trabajo docente o enviar los cambios de este grupo.']];
 page.innerHTML=heading(general?'Gestión general de Secretaría':c.unit?'Consulta de '+(c.unitName||c.unit):'Gestión de '+(data.programs.find(p=>p.id===c.programId)?.nombre||'la carrera'),general?'Estas tareas abarcan la institución. Para trabajar con alumnos o documentos, elige una carrera y grupo.':g?.name||'Grupo seleccionado')+`<div class="secretary-tasks">${actions.map(([route,title,desc])=>`<a class="card link-card" href="#/${route}"><h2>${e(title)} →</h2><p>${e(desc)}</p></a>`).join('')}</div>${!general&&!c.unit?'<section class="card"><h2>Consultar unidades y prácticas</h2><p>Elige una unidad para revisar sus notas, asistencias y formatos. EFSRT dispone de su propio espacio.</p><button id="secretary-units" class="primary">Ver unidades del módulo</button></section>':''}<p class="section-note">${general?'Usa el menú Ámbito de consulta para elegir una carrera.':'Cada registro pertenece al grupo y módulo indicados arriba. Las notas y asistencias las modifica el docente responsable.'}</p>`;
 const button=page.querySelector('#secretary-units');if(button)button.onclick=onUnits;
}
