import {directorGuide} from './director-guide.js';
import {secretariatGuide} from './secretariat-guide.js';
import {chooseUnitWorkspace} from './unit-workspace.js';
export async function chooseWorkspace(root,{api,escape:e,onSelected,role,onLogout,initial={},onBack}){
 const catalog=await api('workspace/options');let year=initial.year||'',program=initial.program||'',module='';
 const years=[...new Set(catalog.groups.map(g=>g.year))].sort().reverse();if(years.length===1)year=years[0];
 const allowed=()=>catalog.groups.filter(g=>(!year||g.year===year)&&(!program||g.programId===program)&&(!module||g.moduleId===module));
 function draw(){const groups=allowed(),pids=new Set(groups.map(g=>g.programId)),programs=catalog.programs.filter(p=>pids.has(p.id));if(!program&&programs.length===1)program=programs[0].id;const mids=new Set(allowed().map(g=>g.moduleId)),modules=catalog.modules.filter(m=>mids.has(m.id));
 root.innerHTML=`<main class="workspace-picker">${role==='SECRETARIA'?secretariatGuide('',true):role==='DIRECTOR'?directorGuide('',true):''}<div class="page-head"><div><div class="eyebrow">TU ESPACIO DE TRABAJO</div><h1>Selecciona el módulo</h1><p>Cada módulo conserva sus alumnos, notas, asistencias y documentos.</p></div></div><div class="card"><div class="form-grid"><label>Año<select id="workspace-year">${years.map(y=>`<option value="${e(y)}" ${year===y?'selected':''}>${e(y)}</option>`).join('')}</select></label><label>Carrera<select id="workspace-program"><option value="">Seleccionar carrera…</option>${programs.map(p=>`<option value="${e(p.id)}" ${program===p.id?'selected':''}>${e(p.nombre)}</option>`).join('')}</select></label></div></div><div class="grid">${year&&program?modules.map(m=>{const gs=allowed().filter(g=>g.moduleId===m.id);return `<section class="card module-card"><div class="eyebrow">${e(gs[0]?.periodId?.endsWith('-II')?'Módulo II':gs[0]?.periodId?.endsWith('-I')?'Módulo I':'Módulo de tu aula')}</div><h2>${e(m.nombre)}</h2><p>${e([...new Set(gs.map(g=>g.periodId))].join(' · '))}</p><p>${gs.length} ${gs.length===1?'aula disponible':'aulas disponibles'}</p><button class="primary" data-module="${e(m.id)}">Entrar a este módulo</button></section>`;}).join(''):'<p>Selecciona el año y la carrera.</p>'}</div><div id="workspace-aulas"></div>${onBack?'<button id="workspace-back">Volver a carreras</button>':''}${role!=='DOCENTE'?'<button id="workspace-overview">Ver toda la institución</button>':''}${!catalog.groups.length?'<div class="card"><p>No tienes aulas asignadas. Dirección debe completar tu asignación.</p><button id="workspace-empty">Volver a mi cuenta</button></div>':''}<button id="workspace-logout">Cerrar sesión</button></main>`;
 const guide=root.querySelector('[data-secretary-guide-context],[data-director-guide-context]');if(guide)guide.onclick=()=>onBack?onBack():root.querySelector('#workspace-program').focus();root.querySelector('#workspace-year').onchange=ev=>{year=ev.target.value;program='';module='';draw();};root.querySelector('#workspace-program').onchange=ev=>{program=ev.target.value;module='';draw();};
 root.querySelectorAll('[data-module]').forEach(b=>b.onclick=async()=>{module=b.dataset.module;const gs=allowed();if(gs.length===1)await apply(gs[0].id);else{const target=root.querySelector('#workspace-aulas');target.innerHTML=`<div class="card"><h2>Selecciona el aula de este módulo</h2><p>Elige el grupo y modalidad con los que trabajarás.</p>${gs.map(g=>`<p><button data-aula="${e(g.id)}">${e(g.name)}</button></p>`).join('')}</div>`;target.querySelectorAll('[data-aula]').forEach(btn=>btn.onclick=()=>apply(btn.dataset.aula));target.scrollIntoView({behavior:'smooth'});}});
 root.querySelector('#workspace-logout').onclick=onLogout;const back=root.querySelector('#workspace-back');if(back)back.onclick=onBack;
 const overview=root.querySelector('#workspace-overview');if(overview)overview.onclick=async()=>{await api('workspace',{overview:true});await onSelected();};const empty=root.querySelector('#workspace-empty');if(empty)empty.onclick=onSelected;
 }
 async function apply(groupId){try{if(role==='SECRETARIA'){await api('workspace',{year,programId:program,moduleId:module,groupId,mode:'MODULE'});await onSelected();return;}await chooseUnitWorkspace(root,{api,escape:e,context:{year,programId:program,moduleId:module,groupId},onSelected,onBack:()=>{module='';draw();},onLogout});}catch(err){const target=root.querySelector('#workspace-aulas');target.innerHTML=`<p class="error">${e(err.message)}</p>`;}}
 if(!year&&years.length)year=years[0];draw();
}
