// Configuración versionada: los planes de otro año tienen identificadores nuevos.
const crypto = require('node:crypto');
const SCHEMAS = {
 moduleDefaults: [['year','Año de referencia','text'],['source','Documento de origen','text'],['notes','Diferencias o datos por confirmar','text'],['dataJson','Valores de referencia editables','json']],
 academicYear: [['institutionJson','Datos institucionales','json'],['calendarJson','Calendarización','json'],['hours','Horas anuales','number'],['credits','Créditos anuales','number'],['directoryDate','Fecha del directorio','date'],['directoryPlace','Lugar del directorio','text']],
 academicPeriod: [['year','Año','text'],['fechaInicio','Inicio','date'],['fechaFin','Término','date'],['hours','Horas declaradas','number'],['credits','Créditos declarados','number']],
 curriculum: [['year','Año','text'],['periodId','Periodo','text'],['nombre','Nombre del módulo','text'],['programName','Programa','text'],['programCode','Código de carrera','text'],['programHours','Horas anuales declaradas del programa','number'],['programCredits','Créditos anuales declarados del programa','number'],['nivelFormativo','Nivel / ciclo','text'],['turno','Turno confirmado','text'],['teacherNames','Docentes de referencia','text'],['hours','Horas declaradas del módulo','number'],['credits','Créditos declarados del módulo','number'],['efsrtHours','Horas EFSRT','number'],['unitsJson','Unidades didácticas y EFSRT','json']],
 personnel: [['year','Año','text'],['name','Apellidos y nombres','text'],['document','DNI','text'],['position','Cargo','text'],['specialty','Especialidad / función','text'],['email','Correo','text'],['phone','Celular','text'],['birthday','Cumpleaños (día y mes; año desconocido)','text'],['address','Domicilio','text'],['referenceTurno','Turno del directorio','text'],['sourceNote','Observación del documento de origen','text']]
};
const schema = Object.fromEntries(Object.entries(SCHEMAS).map(([kind,fields])=>[kind,fields.map(([key,label,type])=>({key,label,type,roles:['DIRECTOR'],options:[]}))]));
const error = (message,status=400)=>{throw Object.assign(new Error(message),{status});};
const date = v => /^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;
function parse(v){try{return JSON.parse(v);}catch{error('Contenido de configuración inválido.');}}
function validate(core,scope,fields){
 if(!schema[scope.kind])return;
 if(!scope.target||scope.unit)error('Identificador de configuración inválido.');
 if(scope.kind==='academicYear'&&!/^\d{4}$/.test(scope.target))error('Año inválido: use cuatro cifras.');
 if(['curriculum','moduleDefaults'].includes(scope.kind)&&!core.record('modules',scope.target))error('Módulo no registrado.');
 if(scope.kind==='curriculum'){const m=core.record('modules',scope.target);if(!fields.nombre||!fields.programName||m.academicYear!==fields.year||!fields.periodId?.startsWith(fields.year+'-'))error('El plan debe conservar el año de su módulo y un periodo válido.');}
 if(fields.year&&!/^\d{4}$/.test(fields.year))error('Año inválido.');
 if(scope.kind==='academicPeriod'&&(!fields.year||!scope.target.startsWith(fields.year+'-')))error('El periodo debe comenzar por su año (ej.: 2026-I).');
 if(scope.kind==='personnel'&&(!fields.name||!/^\d{8}$/.test(fields.document)||scope.target!==fields.year+':'+fields.document))error('Persona inválida: indique nombre, año y DNI de ocho cifras.');
 for(const f of schema[scope.kind])if(f.type==='json'&&fields[f.key]){
  const data=parse(fields[f.key]);
  if(f.key==='dataJson'){if(!data||typeof data!=='object'||Array.isArray(data)||!data.module||!Array.isArray(data.units))error('Referencia del módulo inválida.');const allowed=new Set(['name','hours','credits','theoryHours','practiceHours','capacity','competence','fechaInicio','fechaFin','days','confirmed','dateOrigin',...Array.from({length:5},(_,i)=>'indicator'+(i+1))]);for(const u of data.units){if(!/^UD[1-9]\d*$|^EFSRT$/.test(u.code))error('Código de unidad de referencia inválido.');for(const [k,v]of Object.entries(u)){if(k==='code')continue;if(!allowed.has(k))error('Campo de referencia no permitido: '+k);if(['hours','credits','theoryHours','practiceHours','days'].includes(k)&&v!==null&&(!Number.isFinite(v)||v<0))error('Horas/créditos de referencia inválidos.');if(['fechaInicio','fechaFin'].includes(k)&&v&&!date(v))error('Fecha de referencia inválida.');if(typeof v==='string'&&v.length>2000)error('Referencia demasiado extensa.');}}for(const [k,v]of Object.entries(data.module)){if(!['hours','credits','efsrtHours','competence'].includes(k)||!['string','number'].includes(typeof v)||typeof v==='number'&&(!Number.isFinite(v)||v<0))error('Campo de módulo de referencia inválido.');}}
  if(f.key==='institutionJson'){if(!data||Array.isArray(data)||typeof data!=='object')error('Perfil institucional inválido.');const keys=require('./document-contracts.cjs').SETTINGS_FIELDS.institution.map(f=>f.key);for(const [k,v]of Object.entries(data))if(!keys.includes(k)||typeof v!=='string'||v.length>2000)error('Dato institucional inválido: '+k);}
  if(f.key==='calendarJson'){if(!Array.isArray(data)||data.length>50)error('Calendario inválido.');for(const r of data)if(typeof r.name!=='string'||!r.name.trim()||r.name.length>2000||!date(r.start)||!date(r.end)||r.start>r.end||r.start.slice(0,4)!==scope.target||r.end.slice(0,4)!==scope.target)error('Revise las fechas del calendario y su año.');}
  if(f.key==='unitsJson'){if(!Array.isArray(data)||!data.length||data.length>30)error('Plan de unidades vacío o demasiado extenso.');const codes=new Set();for(const u of data){if(!/^UD[1-9]\d*$|^EFSRT$/.test(u.code)||codes.has(u.code)||typeof u.name!=='string'||!u.name.trim())error('Unidad duplicada o sin nombre.');codes.add(u.code);if(u.confirmed!==undefined&&typeof u.confirmed!=='boolean')error('Estado de confirmación de unidad inválido.');if(u.confirmed===true&&/pendiente de confirmar/i.test(u.name))error('Complete el nombre de la unidad antes de confirmarla.');for(const k of ['hours','credits','theoryHours','practiceHours','days'])if(u[k]!==null&&u[k]!==undefined&&(!Number.isFinite(u[k])||u[k]<0))error('Horas o créditos inválidos.');for(const k of ['fechaInicio','fechaFin'])if(u[k]&&!date(u[k]))error('Fecha de unidad inválida.');if(u.fechaInicio&&u.fechaFin&&u.fechaInicio>u.fechaFin)error('Fechas de unidad invertidas.');}}
 }
 if(scope.kind==='academicPeriod'&&[fields.fechaInicio,fields.fechaFin].filter(Boolean).some(d=>d.slice(0,4)!==fields.year))error('Las fechas deben corresponder al año del periodo.');
 if(scope.kind==='academicPeriod'){for(const r of records(core,'curriculum').filter(r=>r.fields.periodId===scope.target))for(const u of parse(r.fields.unitsJson||'[]'))for(const key of ['fechaInicio','fechaFin'])if(u[key]&&((fields.fechaInicio&&u[key]<fields.fechaInicio)||(fields.fechaFin&&u[key]>fields.fechaFin)))error('El periodo dejaría fuera fechas de unidades existentes. Revise primero su planificación.');}
 if(scope.kind==='academicYear'&&fields.calendarJson){for(const row of parse(fields.calendarJson)){const id=row.name.match(/\((\d{4}-[^)]+)\)/)?.[1],period=id&&core.record('documentSettings','academicPeriod:'+id);if(period)validate(core,period.scope,{...period.fields,fechaInicio:row.start,fechaFin:row.end});}}
 if(scope.kind==='curriculum'&&core.records('groups').some(g=>g.moduleId===scope.target&&g.periodId!==fields.periodId))error('Un aula ya utiliza el periodo de este plan. Prepare otro módulo para cambiar de periodo.');
 if(scope.kind==='curriculum'&&fields.unitsJson){const units=parse(fields.unitsJson),codes=new Set(units.map(u=>u.code));if(!codes.has('EFSRT'))error('El plan debe incluir EFSRT.');if(core.records('groups').some(g=>g.moduleId===scope.target&&g.units.some(u=>!codes.has(u))))error('No retire una unidad utilizada por un aula. Cree un plan nuevo.');const period=core.record('documentSettings','academicPeriod:'+fields.periodId)?.fields;for(const u of units)for(const key of ['fechaInicio','fechaFin'])if(u[key]&&(u[key].slice(0,4)!==fields.year||(period?.fechaInicio&&u[key]<period.fechaInicio)||(period?.fechaFin&&u[key]>period.fechaFin)))error('La fecha de una unidad está fuera del periodo.');}
}
function synchronize(core,actor,saved){const {scope,fields}=saved;if(scope.kind==='curriculum'){const m=core.record('modules',scope.target);if(m.nombre!==fields.nombre)core.write(actor,'modules',{...m,nombre:fields.nombre},m.rev);const p=core.record('programs',m.programaId);if(p.nombre!==fields.programName){core.write(actor,'programs',{...p,nombre:fields.programName},p.rev);for(const r of records(core,'curriculum').filter(r=>r.id!==saved.id&&core.record('modules',r.scope.target)?.programaId===p.id))core.write(actor,'documentSettings',{...r,fields:{...r.fields,programName:fields.programName}},r.rev);}}
 if(scope.kind==='academicPeriod'){const year=core.record('documentSettings','academicYear:'+fields.year);if(year&&fields.fechaInicio&&fields.fechaFin){const rows=parse(year.fields.calendarJson||'[]'),i=rows.findIndex(r=>r.name.includes('('+scope.target+')'));const row={name:i>=0?rows[i].name:'Periodo académico ('+scope.target+')',start:fields.fechaInicio,end:fields.fechaFin,detail:i>=0?rows[i].detail||'':''};if(i>=0)rows[i]=row;else rows.push(row);core.write(actor,'documentSettings',{...year,fields:{...year.fields,calendarJson:JSON.stringify(rows)}},year.rev);}}
 if(scope.kind==='academicYear'&&fields.calendarJson){for(const row of parse(fields.calendarJson)){const id=row.name.match(/\((\d{4}-[^)]+)\)/)?.[1],period=id&&core.record('documentSettings','academicPeriod:'+id);if(period&&(period.fields.fechaInicio!==row.start||period.fields.fechaFin!==row.end))core.write(actor,'documentSettings',{...period,fields:{...period.fields,fechaInicio:row.start,fechaFin:row.end}},period.rev);}}
}
function records(core,kind){return core.records('documentSettings').filter(r=>r.scope.kind===kind&&!r.archived);}
function issues(core,year){const out=[];for(const r of records(core,'curriculum').filter(r=>r.fields.year===year)){const f=r.fields,units=parse(f.unitsJson||'[]');for(const key of ['hours','credits']){const values=units.map(u=>u[key]),sum=values.reduce((n,v)=>n+(typeof v==='number'?v:0),0);if(values.some(v=>typeof v!=='number'))out.push(`${f.programName} / ${f.nombre}: faltan ${key==='hours'?'horas':'créditos'} en algunas unidades.`);else if(typeof f[key]==='number'&&sum!==f[key])out.push(`${f.programName} / ${f.nombre}: suma ${sum} ${key==='hours'?'horas':'créditos'}; total declarado ${f[key]}.`);}if(units.some(u=>!u.fechaInicio||!u.fechaFin))out.push(`${f.programName} / ${f.nombre}: faltan fechas de unidades.`);if(!f.turno)out.push(`${f.programName} / ${f.nombre}: turno pendiente.`);}return out;}
function configuration(core,actor){core.requireRole(actor,['DIRECTOR','SECRETARIA']);return {editable:actor.role==='DIRECTOR',schema,institutionSchema:require('./document-contracts.cjs').SETTINGS_FIELDS.institution,records:core.records('documentSettings').filter(r=>schema[r.scope.kind]&&!r.archived),issues:Object.fromEntries(records(core,'academicYear').map(r=>[r.scope.target,issues(core,r.scope.target)]))};}
function cloneYear(core,actor,input){core.requireRole(actor,['DIRECTOR']);if(!core.status().authority)error('Cree el año desde el equipo institucional.',403);if(!/^\d{4}$/.test(input.year)||records(core,'academicYear').some(r=>r.scope.target===input.year))error('Año inválido o ya registrado.');const source=records(core,'academicYear').find(r=>r.scope.target===input.sourceYear);if(!source)error('Seleccione un año de origen.');const D=require('./offline-documents.cjs');core.createBackup(actor,'antes-nuevo-año');return core.transaction(()=>{
 const save=(kind,target,fields)=>D.saveSettings(core,actor,{scope:{kind,target},fields,rev:null});
 save('academicYear',input.year,{...source.fields,calendarJson:'[]',directoryDate:''});
 for(const p of records(core,'academicPeriod').filter(r=>r.fields.year===input.sourceYear))save('academicPeriod',input.year+p.scope.target.slice(4),{...p.fields,year:input.year,fechaInicio:'',fechaFin:''});
 const programs=new Map();for(const r of records(core,'curriculum').filter(r=>r.fields.year===input.sourceYear)){const old=core.record('modules',r.scope.target),id='MOD-'+input.year+'-'+crypto.randomUUID();if(!programs.has(old.programaId)){const previous=core.record('programs',old.programaId),pid='PROG-'+input.year+'-'+crypto.randomUUID();core.write(actor,'programs',{id:pid,nombre:previous.nombre,academicYear:input.year});programs.set(old.programaId,pid);}core.write(actor,'modules',{id,nombre:old.nombre,programaId:programs.get(old.programaId),academicYear:input.year});save('curriculum',id,{...r.fields,year:input.year,periodId:input.year+r.fields.periodId.slice(4),unitsJson:JSON.stringify(parse(r.fields.unitsJson).map(u=>({...u,fechaInicio:'',fechaFin:'',dateOrigin:''})))});const ref=core.record('documentSettings','moduleDefaults:'+old.id);if(ref){const data=parse(ref.fields.dataJson);data.units=data.units.map(u=>({...u,fechaInicio:'',fechaFin:'',dateOrigin:''}));save('moduleDefaults',id,{...ref.fields,year:input.year,dataJson:JSON.stringify(data)});}}
 for(const p of records(core,'personnel').filter(r=>r.fields.year===input.sourceYear))save('personnel',input.year+':'+p.fields.document,{...p.fields,year:input.year});
 return {year:input.year,message:'Año creado. Complete fechas, grupos, secciones y asignaciones; el historial anterior se conserva.'};
 });}
module.exports={schema,validate,configuration,cloneYear,issues,parse,synchronize};
