const crypto=require('node:crypto');
const SCHEMA_VERSION=1;
function protectDatabase(db){
 const version=db.prepare('PRAGMA user_version').get().user_version;if(version>SCHEMA_VERSION)throw Error('Esta base usa una versión más nueva. Instale una versión compatible antes de abrirla.');
 db.exec('PRAGMA busy_timeout=5000; PRAGMA foreign_keys=ON;');
 const check=db.prepare('PRAGMA quick_check').all();if(check.some(r=>Object.values(r)[0]!=='ok'))throw Error('La base no superó la comprobación física. Conserve sus archivos y recupere una copia verificada.');
 for(const table of ['settings','users','records','operations','conflicts','audit']){if(db.prepare(`SELECT COUNT(*) AS n FROM ${table} WHERE NOT json_valid(value)`).get().n)throw Error('Datos internos inválidos en '+table+'. Recupere una copia verificada.');for(const action of ['INSERT','UPDATE'])db.exec(`CREATE TRIGGER IF NOT EXISTS guard_${table}_${action.toLowerCase()} BEFORE ${action} ON ${table} WHEN NOT json_valid(NEW.value) BEGIN SELECT RAISE(ABORT,'JSON interno invalido'); END;`);}
 for(const action of ['INSERT','UPDATE']){
  db.exec(`CREATE TRIGGER IF NOT EXISTS guard_record_id_${action.toLowerCase()} BEFORE ${action} ON records WHEN json_type(NEW.value,'$.id') IS NULL OR CAST(json_extract(NEW.value,'$.id') AS TEXT)!=NEW.id BEGIN SELECT RAISE(ABORT,'Identificador de registro inconsistente'); END;`);
  db.exec(`CREATE TRIGGER IF NOT EXISTS guard_user_shape_${action.toLowerCase()} BEFORE ${action} ON users WHEN json_extract(NEW.value,'$.role') IS NULL OR json_extract(NEW.value,'$.role') NOT IN ('DIRECTOR','SECRETARIA','DOCENTE') OR json_type(NEW.value,'$.version') IS NULL OR json_type(NEW.value,'$.version')!='integer' OR json_extract(NEW.value,'$.version')<1 OR json_type(NEW.value,'$.active') IS NULL OR json_type(NEW.value,'$.active') NOT IN ('true','false') BEGIN SELECT RAISE(ABORT,'Estructura de cuenta invalida'); END;`);
  db.exec(`CREATE TRIGGER IF NOT EXISTS guard_user_identity_${action.toLowerCase()} BEFORE ${action} ON users WHEN json_type(NEW.value,'$.id') IS NULL OR CAST(json_extract(NEW.value,'$.id') AS TEXT)!=NEW.id OR json_extract(NEW.value,'$.username') IS NULL OR json_extract(NEW.value,'$.username')!=NEW.username OR json_extract(NEW.value,'$.role') NOT IN ('DIRECTOR','SECRETARIA','DOCENTE') OR json_extract(NEW.value,'$.version')<1 BEGIN SELECT RAISE(ABORT,'Cuenta interna inconsistente'); END;`);
 }
 db.exec(`CREATE INDEX IF NOT EXISTS idx_records_group ON records(entity,json_extract(value,'$.groupId')); CREATE INDEX IF NOT EXISTS idx_records_student ON records(entity,json_extract(value,'$.studentId'));`);
 db.exec(`PRAGMA user_version=${SCHEMA_VERSION}`);
}
function inspectDatabase(core){
 const errors=[],warnings=[],add=(list,code,entity,id,message)=>list.push({code,entity,id,message});
 const groups=new Map(core.records('groups').map(r=>[r.id,r])),students=new Map(core.records('students').map(r=>[r.id,r])),enrollments=new Map(core.records('enrollments').map(r=>[r.id,r])),programs=new Map(core.records('programs').map(r=>[r.id,r])),modules=new Map(core.records('modules').map(r=>[r.id,r]));
 for(const g of groups.values()){if(!programs.has(g.programId))add(errors,'PROGRAM_MISSING','groups',g.id,'La carrera del grupo no existe.');if(g.moduleId&&!modules.has(g.moduleId))add(errors,'MODULE_MISSING','groups',g.id,'El módulo del grupo no existe.');if(g.moduleId&&modules.get(g.moduleId)?.programaId!==g.programId)add(errors,'MODULE_PROGRAM','groups',g.id,'El módulo no pertenece a la carrera.');if(!g.periodId||!g.moduleId||!g.units?.length)add(warnings,'GROUP_INCOMPLETE','groups',g.id,'Configure periodo, módulo y unidades antes de utilizar el aula.');if(!core.groupSection(g))add(warnings,'SECTION_PENDING','groups',g.id,'Falta confirmar la sección del aula.');}
 const activePairs=new Map();for(const en of enrollments.values()){if(!students.has(en.studentId)||!groups.has(en.groupId))add(errors,'ENROLLMENT_PARENT','enrollments',en.id,'La matrícula no tiene alumno o grupo válido.');const group=groups.get(en.groupId);if(group&&en.periodId&&group.periodId&&en.periodId!==group.periodId)add(errors,'ENROLLMENT_PERIOD','enrollments',en.id,'La matrícula y el grupo tienen periodos diferentes.');if(en.active){const key=en.studentId+'|'+en.groupId;if(activePairs.has(key))add(en.legacy&&activePairs.get(key).legacy&&!en.periodId&&!activePairs.get(key).periodId?warnings:errors,'DUPLICATE_ENROLLMENT','enrollments',en.id,'Hay dos matrículas activas del mismo alumno en la misma aula.');activePairs.set(key,en);}}
 for(const entity of ['grades','attendance'])for(const r of core.records(entity)){const en=enrollments.get(r.enrollmentId),g=groups.get(r.groupId);if(!en||!g||en.groupId!==r.groupId)add(errors,'ACADEMIC_PARENT',entity,r.id,'El registro académico no coincide con su matrícula y aula.');if(g?.units?.length&&!g.units.includes(r.unit))add(errors,'ACADEMIC_UNIT',entity,r.id,'La unidad no corresponde al grupo.');if(r.periodId&&g?.periodId&&r.periodId!==g.periodId)add(errors,'ACADEMIC_PERIOD',entity,r.id,'El registro académico y el grupo tienen periodos diferentes.');if(entity==='grades'&&!(r.value===null&&r.pending===true)&&(!Number.isFinite(r.value)||r.value<0||r.value>20))add(errors,'GRADE_VALUE',entity,r.id,'Nota fuera de la escala válida.');if(entity==='attendance'&&!(r.value===null&&r.pending===true)&&!['P','F','J','T'].includes(r.value))add(errors,'ATTENDANCE_VALUE',entity,r.id,'Marca de asistencia inválida.');const identity=crypto.createHash('sha256').update(JSON.stringify([entity,r.enrollmentId,r.unit,entity==='grades'?r.indicator:[r.date,r.session]])).digest('hex');if(identity!==r.id)add(errors,'ACADEMIC_ID',entity,r.id,'El identificador académico no corresponde a su contenido.');}
 const documents=new Map();for(const s of students.values()){if(documents.has(s.document))add(warnings,'HISTORICAL_DOCUMENT_DUPLICATE','students',s.id,'Documento repetido: conciliar conservando los historiales.');documents.set(s.document,s.id);}
 for(const user of core.users())for(const a of user.assignments||[]){const g=groups.get(a.groupId);if(!g||a.units?.some(u=>!g.units.includes(u)))add(errors,'ASSIGNMENT_PARENT','users',user.id,'Asignación docente con grupo o unidades inexistentes.');if(a.section&&g&&a.section!==core.groupSection(g))add(errors,'ASSIGNMENT_SECTION','users',user.id,'La sección del docente no coincide con su aula.');}
 const physical=core.db.prepare('PRAGMA quick_check').all().every(r=>Object.values(r)[0]==='ok');return {at:new Date().toISOString(),schemaVersion:core.db.prepare('PRAGMA user_version').get().user_version,physicalIntegrity:physical,healthy:physical&&!errors.length,errors,warnings,counts:{students:students.size,enrollments:enrollments.size,groups:groups.size,grades:core.records('grades').length,attendance:core.records('attendance').length},journalMode:core.db.prepare('PRAGMA journal_mode').get().journal_mode};
}
module.exports={protectDatabase,inspectDatabase,SCHEMA_VERSION};
