const POLICY={
 DIRECTOR:{routes:['inicio','estudiantes','matriculas','grupos','evaluacion','asistencia','documentos','configuracion-documental','entregas','datos','cuentas','sincronizacion','respaldo','perfil'],settings:['institution','program','module','group','unit','unitCurriculum','enrollment','registry','practice','closure'],imports:['estudiantes','docentes'],users:['DIRECTOR','SECRETARIA','DOCENTE']},
 SECRETARIA:{routes:['inicio','estudiantes','matriculas','grupos','evaluacion','asistencia','documentos','configuracion-documental','entregas','datos','cuentas','sincronizacion','perfil'],settings:['group','enrollment'],imports:['estudiantes','docentes'],users:['DOCENTE']},
 DOCENTE:{routes:['inicio','estudiantes','grupos','evaluacion','asistencia','documentos','configuracion-documental','entregas','datos','sincronizacion','perfil'],settings:['unit','practice'],imports:['estudiantes','notas','asistencias'],users:[]}
};
function policyFor(user){const p=POLICY[user.role];return {...p,settings:user.role==='DOCENTE'&&!user.assignments?.some(a=>a.units.includes('EFSRT'))?['unit']:p.settings};}
function groupName(core,g){const p=core.record('programs',g.programId)?.nombre||'Programa';const clean=v=>v&&v!=='PENDIENTE'?v:'';const human=g.name&&!/^GRP-|^GAC-|^G-\w/.test(g.name)?g.name:'';return [p,human||'Grupo '+String(g.id).replace(/^.*-/,'').slice(-3),core.groupSection(g)?'Sección '+core.groupSection(g):'',clean(g.turno),clean(g.modalidad),clean(g.periodId)].filter(Boolean).join(' · ');}
function enrollmentCode(core,studentId,enrollmentId){const s=core.record('students',studentId);if(!s)return '';const document=String(s.document).trim().replace(/\s/g,'');const entries=core.records('enrollments').filter(e=>e.studentId===studentId).sort((a,b)=>(a.createdAt||a.legacy?.fechaCreacion||a.id).localeCompare(b.createdAt||b.legacy?.fechaCreacion||b.id));const n=entries.findIndex(e=>e.id===enrollmentId);return `MAT-${document}-${String(n<0?entries.length+1:n+1).padStart(3,'0')}`;}
module.exports={POLICY,policyFor,groupName,enrollmentCode};
