// Adaptador de intercambio: no ejecuta fórmulas ni macros y nunca escribe entradas del ZIP al disco.
const zlib=require('node:zlib'),fs=require('node:fs'),path=require('node:path');
const {SCHEMAS,headerName}=require('./update-schema.cjs');
const limit=32*1024*1024;
// Excel admite prefijos arbitrarios para el espacio de nombres principal.
const normalizeXML=s=>String(s).replace(/(<\/?)[\w]+:(?=[\w]+(?:\s|\/?>))/g,'$1').replace(/xmlns:x=/g,'xmlns=');
const xml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const unxml=s=>String(s).replace(/&#(x[0-9a-f]+|\d+);/gi,(_,v)=>String.fromCodePoint(v[0].toLowerCase()==='x'?parseInt(v.slice(1),16):Number(v))).replace(/&(amp|lt|gt|quot|apos);/g,(_,v)=>({amp:'&',lt:'<',gt:'>',quot:'"',apos:"'"}[v]));
function csvRows(text,delimiter){text=String(text).replace(/^\ufeff/,'');if(!delimiter){const first=text.split(/\r?\n/)[0];delimiter=['\t',';',','].sort((a,b)=>first.split(b).length-first.split(a).length)[0];}const rows=[];let row=[],cell='',quote=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quote&&text[i+1]==='"'){cell+='"';i++;}else quote=!quote;}else if(!quote&&c===delimiter){row.push(cell);cell='';}else if(!quote&&(c==='\n'||c==='\r')){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v!==''))rows.push(row);row=[];cell='';}else cell+=c;}if(quote)throw Error('Hay comillas sin cerrar en la tabla.');row.push(cell);if(row.some(v=>v!==''))rows.push(row);return rows;}
function objects(rows){if(!rows.length)return [];const headers=rows[0].map(headerName);if(new Set(headers).size!==headers.length)throw Error('La tabla contiene encabezados duplicados.');if(rows.length>20001||headers.length>64)throw Error('La tabla supera el tamaño permitido.');return rows.slice(1).filter(row=>row.some(v=>v!==''&&v!=null)).map((row,i)=>({rowNumber:i+2,...Object.fromEntries(headers.map((h,j)=>[h,row[j]??'']))}));}
function unzip(bytes){if(bytes.length>limit)throw Error('Archivo demasiado grande.');let end=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(bytes.readUInt32LE(i)===0x06054b50){end=i;break;}if(end<0)throw Error('El archivo no es un XLSX válido.');let offset=bytes.readUInt32LE(end+16),total=0;const entries=new Map(),count=bytes.readUInt16LE(end+10);if(count>1000)throw Error('El archivo contiene demasiadas entradas.');for(let i=0;i<count;i++){if(bytes.readUInt32LE(offset)!==0x02014b50)throw Error('Directorio ZIP inválido.');const flags=bytes.readUInt16LE(offset+8),method=bytes.readUInt16LE(offset+10),compressed=bytes.readUInt32LE(offset+20),size=bytes.readUInt32LE(offset+24),length=bytes.readUInt16LE(offset+28),extra=bytes.readUInt16LE(offset+30),comment=bytes.readUInt16LE(offset+32),start=bytes.readUInt32LE(offset+42),name=bytes.subarray(offset+46,offset+46+length).toString();if(flags&1||size>limit||compressed>limit||(total+=size)>limit||entries.has(name))throw Error('El XLSX está cifrado, duplicado o supera el límite.');if(bytes.readUInt32LE(start)!==0x04034b50)throw Error('Entrada ZIP inválida.');const dataStart=start+30+bytes.readUInt16LE(start+26)+bytes.readUInt16LE(start+28),raw=bytes.subarray(dataStart,dataStart+compressed);const data=method===0?raw:method===8?zlib.inflateRawSync(raw,{maxOutputLength:limit}):null;if(!data||data.length!==size)throw Error('Compresión XLSX no compatible.');entries.set(name,data);offset+=46+length+extra+comment;}return entries;}
function columnNumber(ref){let n=0;for(const c of ref.replace(/\d/g,''))n=n*26+c.charCodeAt(0)-64;return n-1;}
function columnName(n){let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;}
function worksheetRows(text,strings){if(/<!DOCTYPE|<!ENTITY/i.test(text))throw Error('XML con entidades no permitido.');const rows=[];for(const row of text.matchAll(/<(?:\w+:)?row\b[^>]*>([\s\S]*?)<\/(?:\w+:)?row>/g)){const cells=[];for(const cell of row[1].matchAll(/<(?:\w+:)?c\b(?![^>]*\/>)([^>]*)>([\s\S]*?)<\/(?:\w+:)?c>/g)){const ref=/\br="([A-Z]+\d+)"/.exec(cell[1])?.[1];if(!ref)continue;if(/<(?:\w+:)?f\b/.test(cell[2]))throw Error('Las tablas de actualización deben contener valores, no fórmulas.');const type=/\bt="([^"]+)"/.exec(cell[1])?.[1];let value=/<(?:\w+:)?v[^>]*>([\s\S]*?)<\/(?:\w+:)?v>/.exec(cell[2])?.[1]||'';if(type==='s')value=strings[Number(value)]??'';else if(type==='inlineStr')value=[...cell[2].matchAll(/<(?:\w+:)?t\b[^>]*>([\s\S]*?)<\/(?:\w+:)?t>/g)].map(m=>unxml(m[1])).join('');else if(type==='str')value=unxml(value);else if(value!=='')value=Number.isFinite(Number(value))?Number(value):unxml(value);cells[columnNumber(ref)]=value;}rows.push(cells);}return rows;}
function readXlsx(bytes,sheetName='Datos'){const entries=unzip(bytes);if(entries.has('xl/vbaProject.bin'))throw Error('No se aceptan macros.');const strings=[...(normalizeXML(entries.get('xl/sharedStrings.xml')?.toString()||'')).matchAll(/<si\b[^>]*>([\s\S]*?)<\/si>/g)].map(m=>[...m[1].matchAll(/<t\b[^>]*>([\s\S]*?)<\/t>/g)].map(t=>unxml(t[1])).join(''));const workbook=normalizeXML(entries.get('xl/workbook.xml')?.toString()||''),rels=normalizeXML(entries.get('xl/_rels/workbook.xml.rels')?.toString()||'');const sheets=[...workbook.matchAll(/<sheet\b([^>]+)\/?\s*>/g)].map(m=>({name:unxml(/\bname="([^"]+)"/.exec(m[1])?.[1]||''),rid:/\br:id="([^"]+)"/.exec(m[1])?.[1]}));const selected=sheets.find(s=>s.name===sheetName)||sheets[0];if(!selected)throw Error('El XLSX no tiene hojas.');const relationship=[...rels.matchAll(/<Relationship\b([^>]+)\/?\s*>/g)].find(m=>/\bId="([^"]+)"/.exec(m[1])?.[1]===selected.rid),target=/\bTarget="([^"]+)"/.exec(relationship?.[1]||'')?.[1];const file=target?(target.startsWith('/')?target.slice(1):path.posix.normalize('xl/'+target)):null;const worksheet=file&&entries.get(file);if(!worksheet)throw Error('No se encontró la hoja de datos.');return objects(worksheetRows(worksheet.toString(),strings));}
function readTable(input){if(input.format==='xlsx')return readXlsx(Buffer.from(input.content,'base64'),input.sheetName);if(input.format==='json'){const value=typeof input.content==='string'?JSON.parse(input.content):input.content;if(value.version&&value.version!==1)throw Error('Versión de plantilla incompatible.');const rows=Array.isArray(value)?value:value.rows;if(!Array.isArray(rows))throw Error('El JSON debe contener una lista rows.');return rows.map((r,i)=>({rowNumber:i+1,...Object.fromEntries(Object.entries(r).map(([k,v])=>[headerName(k),v]))}));}return objects(csvRows(input.content));}
function csv(headers,rows){const cell=v=>{let s=String(v??'');if(/^[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};return '\ufeff'+[headers,...rows.map(r=>headers.map(h=>r[h]??''))].map(r=>r.map(cell).join(';')).join('\r\n');}
const crcTable=Array.from({length:256},(_,n)=>{for(let j=0;j<8;j++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});function crc32(buf){let crc=0xffffffff;for(const b of buf)crc=crcTable[(crc^b)&255]^(crc>>>8);return (crc^0xffffffff)>>>0;}
function zip(entries){const locals=[],directory=[];let offset=0;for(const [name,data]of entries){const file=Buffer.from(name),compressed=zlib.deflateRawSync(data),crc=crc32(data),header=Buffer.alloc(30);header.writeUInt32LE(0x04034b50);header.writeUInt16LE(20,4);header.writeUInt16LE(0x800,6);header.writeUInt16LE(8,8);header.writeUInt32LE(crc,14);header.writeUInt32LE(compressed.length,18);header.writeUInt32LE(data.length,22);header.writeUInt16LE(file.length,26);locals.push(header,file,compressed);const central=Buffer.alloc(46);central.writeUInt32LE(0x02014b50);central.writeUInt16LE(20,4);central.writeUInt16LE(20,6);central.writeUInt16LE(0x800,8);central.writeUInt16LE(8,10);central.writeUInt32LE(crc,16);central.writeUInt32LE(compressed.length,20);central.writeUInt32LE(data.length,24);central.writeUInt16LE(file.length,28);central.writeUInt32LE(offset,42);directory.push(central,file);offset+=header.length+file.length+compressed.length;}const dir=Buffer.concat(directory),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(entries.size,8);end.writeUInt16LE(entries.size,10);end.writeUInt32LE(dir.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...locals,dir,end]);}
function fillTemplate(templateFile,headers,rows){const entries=unzip(fs.readFileSync(templateFile)),sheet=normalizeXML(entries.get('xl/worksheets/sheet1.xml')?.toString()||'');if(!sheet)throw Error('Plantilla XLSX no disponible.');const oldRows=worksheetRows(sheet,[]);const styleByCol=new Map();const headerXML=/<row\b[^>]*r="1"[^>]*>([\s\S]*?)<\/row>/.exec(sheet)?.[1]||'';for(const cell of headerXML.matchAll(/<c\b([^>]+)>/g)){const ref=/\br="([A-Z]+1)"/.exec(cell[1])?.[1],style=/\bs="(\d+)"/.exec(cell[1])?.[1];if(ref&&style)styleByCol.set(columnNumber(ref),style);}
 let body='';for(const [i,row]of [headers,...rows.map(r=>headers.map(h=>r[h]??''))].entries()){body+=`<row r="${i+1}">`+row.map((v,j)=>{const ref=columnName(j)+(i+1);return typeof v==='number'&&Number.isFinite(v)?`<c r="${ref}"><v>${v}</v></c>`:`<c r="${ref}" t="inlineStr"${i===0&&styleByCol.has(j)?' s="'+styleByCol.get(j)+'"':''}><is><t xml:space="preserve">${xml(v)}</t></is></c>`;}).join('')+'</row>';}
 const last=columnName(headers.length-1)+(rows.length+1);let updated=sheet.replace(/<sheetData[^>]*>[\s\S]*?<\/sheetData>/,`<sheetData>${body}</sheetData>`).replace(/<dimension[^>]*\/>/,`<dimension ref="A1:${last}"/>`);entries.set('xl/worksheets/sheet1.xml',Buffer.from(updated));for(const [name,bytes]of entries)if(/^xl\/tables\/table\d+\.xml$/.test(name))entries.set(name,Buffer.from(bytes.toString().replace(/ref="A1:[A-Z]+\d+"/g,`ref="A1:${last}"`)));return zip(entries);}
module.exports={readTable,csv,SCHEMAS,readXlsx,fillTemplate,unzip,zip};
