const SCHEMAS={
 estudiantes:{label:'Estudiantes y matrículas',columns:['accion','tipo_documento','dni','apellido_paterno','apellido_materno','nombres','nombre_completo','sexo','fecha_nacimiento','grupo_id','fecha_ingreso','revision_estudiante'],required:['dni','grupo_id'],identity:['tipo_documento','dni','grupo_id'],example:{accion:'EJEMPLO_NO_IMPORTAR',tipo_documento:'DNI',dni:'00112233',apellido_paterno:'Apellido',apellido_materno:'Ejemplo',nombres:'Nombre',sexo:'H',fecha_nacimiento:'2000-01-15',grupo_id:'Seleccione un grupo del catálogo',fecha_ingreso:'2026-10-06'}},
 docentes:{label:'Docentes y asignaciones',columns:['accion','usuario','nombre_profesor','descripcion','programa_id','grupo_id','unidades','revision_usuario'],required:['usuario','nombre_profesor','programa_id','grupo_id','unidades'],identity:['usuario','grupo_id'],example:{accion:'EJEMPLO_NO_IMPORTAR',usuario:'docente.ejemplo',nombre_profesor:'Profesor de ejemplo',descripcion:'Docente de Informática, grupo A, turno mañana',programa_id:'PROG-005',grupo_id:'Seleccione un grupo del catálogo',unidades:'UD1;UD2'}},
 notas:{label:'Notas por indicador',columns:['accion','matricula_id','dni','grupo_id','unidad','indicador','nota','observacion','revision'],required:['grupo_id','unidad','indicador','nota'],identity:['matricula_id','grupo_id','unidad','indicador'],example:{accion:'EJEMPLO_NO_IMPORTAR',matricula_id:'No modifique el identificador',dni:'00112233',grupo_id:'Seleccione un grupo del catálogo',unidad:'UD1',indicador:'IL1.IA1',nota:16,observacion:'',revision:'Conserve la revisión del registro'}},
 asistencias:{label:'Asistencias por sesión',columns:['accion','matricula_id','dni','grupo_id','unidad','fecha','sesion','estado','observacion','revision'],required:['grupo_id','unidad','fecha','sesion','estado'],identity:['matricula_id','grupo_id','unidad','fecha','sesion'],example:{accion:'EJEMPLO_NO_IMPORTAR',matricula_id:'No modifique el identificador',dni:'00112233',grupo_id:'Seleccione un grupo del catálogo',unidad:'UD1',fecha:'2026-10-06',sesion:'1',estado:'P',revision:'Conserve la revisión del registro'}}
};
const aliases={documento:'dni',numero_documento:'dni',numerodocumento:'dni',document:'dni',apellidoPaterno:'apellido_paterno',apellidoMaterno:'apellido_materno',nombre:'nombre_completo',name:'nombre_completo',profesor:'nombre_profesor',grupo:'grupo_id',groupid:'grupo_id',group_id:'grupo_id',programaid:'programa_id',username:'usuario',nota_final:'nota',state:'estado'};
const normalized=h=>String(h).trim().replace(/([a-z])([A-Z])/g,'$1_$2').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[\s\-]+/g,'_');
function headerName(h){const v=normalized(h);return aliases[h]||aliases[v]||v;}
module.exports={SCHEMAS,headerName};
