const fs=require('node:fs'),path=require('node:path'),{OfflineCore}=require('../../scripts/offline-core.cjs'),D=require('../../scripts/offline-documents.cjs');
function createPdfFixture(directory){const c=new OfflineCore(fs.mkdtempSync(path.join(directory,'db-')));c.setup({username:'director',name:'Dirección de ensayo',password:'password-test-123',institutionName:'CETPRO DE ENSAYO'});const director=c.users()[0],p=c.records('programs').find(p=>p.id==='PROG-005'),m=c.records('modules').find(m=>m.id==='MOD-009');
 const group=c.saveGroup(director,{name:'Grupo de ensayo',programId:p.id,moduleId:m.id,periodId:'2026-I',units:['UD1','UD2','UD3','UD4','UD5','UD6','UD7','EFSRT']});
 const student=c.saveStudent(director,{name:'Apellido Ensayo, Alumna',document:'PRUEBA-01',lastName1:'Apellido',lastName2:'Ensayo',firstNames:'Alumna',sex:'M',birthDate:'2000-01-02',documentType:'PRUEBA'});const enrollment=c.enroll(director,{studentId:student.id,groupId:group.id,startDate:'2026-03-01'});const teacher=c.saveUser(director,{username:'docente',name:'Docente de ensayo',password:'docente-test-123',role:'DOCENTE',assignments:[{groupId:group.id,units:group.units}]});const docente=c.user(teacher.id);
 const put=(kind,target,fields,unit)=>D.saveSettings(c,director,{scope:{kind,...(target?{target}:{}),...(unit?{unit}:{})},fields,rev:c.record('documentSettings',D.idFor({kind,target,unit}))?.rev||null});
 put('institution',null,{nombre:'CETPRO DE ENSAYO',tipoGestion:'PÚBLICA',codigoModular:'TEST001',dre:'DRE ENSAYO',ugel:'UGEL ENSAYO',region:'Región ensayo',departamento:'Departamento ensayo',provincia:'Provincia ensayo',distrito:'Distrito ensayo',lugar:'Lugar ensayo',direccion:'Dirección de ensayo',resolucionAutorizacion:'RES-TEST-001',resolucionConversion:'RES-TEST-002'});
 put('program',p.id,{nivelFormativo:'Nivel de ensayo',tipoPlan:'Plan de ensayo',resolucionPrograma:'RES-PROG-TEST',officialTitleText:'TÉCNICO DE ENSAYO'});
 put('module',m.id,{hours:210,credits:7,efsrtHours:30,competence:'Competencia confirmada de ensayo',resolucionAutorizacion:'RES-MOD-TEST',presenceStates:'P,T',absenceStates:'F,J',absenceDenominator:'PROGRAMADAS',approvalMinimum:13});
 put('group',group.id,{ciclo:'Ciclo de ensayo',seccion:'A',turno:'Mañana',modalidad:'Presencial',fechaInicio:'2026-03-01',fechaFin:'2026-07-31',periodClase:'Marzo - Julio',teacherName:'Docente de ensayo',efsrtInicio:'2026-04-01',efsrtFin:'2026-06-01'});
 for(const unit of group.units.filter(u=>u!=='EFSRT')){put('unit',group.id,{name:'Unidad de ensayo '+unit,capacity:'Opera herramientas del módulo',competence:'Competencia '+unit,...Object.fromEntries(Array.from({length:5},(_,i)=>['indicator'+(i+1),'Indicador de ensayo '+(i+1)]))},unit);put('unitCurriculum',group.id,{hours:30,credits:1},unit);
 c.saveAcademic(docente,'grades',{groupId:group.id,unit,rows:Array.from({length:5},(_,i)=>['IA1','IA2','IA3','','RECOVERY'].map(k=>({enrollmentId:enrollment.id,indicator:`IL${i+1}${k?'.'+k:''}`,value:k==='RECOVERY'?null:16.5,clear:k==='RECOVERY'}))).flat().concat([{enrollmentId:enrollment.id,indicator:'RESULTADO_UD',value:16.5}])});
 c.saveAcademic(docente,'attendance',{groupId:group.id,unit,date:'2026-03-02',session:'1',rows:[{enrollmentId:enrollment.id,value:'P'}]});}
 put('enrollment',enrollment.id,{condition:'G',emissionDate:'2026-07-31'});put('registry',enrollment.id,{registerCode:'REG-TEST-001',registryBook:'Libro de ensayo',registryFolio:'F01',registryNumber:'N01',registryDate:'2026-07-31',registryAsiento:'Asiento de ensayo'});
 put('practice',enrollment.id,{companyName:'EMPRESA DE ENSAYO',companyAddress:'DIRECCIÓN DE ENSAYO',...Object.fromEntries([3,2,2,3,3,3,1,2,1].map((v,i)=>['criterion'+(i+1),v])),efsrtFinalGrade:17});put('closure',enrollment.id,{modularGrade:16.5,approvedUnitsCount:7,failedUnitsCount:0,observations:'Datos de prueba'});
 return {c,director,docente,group,enrollment,put};}
module.exports={createPdfFixture};
